### ISSUE TITLE
Get-GSUser with first and last name

### ISSUE THREAD

**Issue by cooper** [scrthq/PSGSuite#10]
Is it possible to call Get-GSUser to fetch info for a user based on first and last name rather than username?

**Comment by scrthq** [comment]
Hey Cooper,

With the current released version, Get-GSUser is limited to what Google `get user` API call options are (which necessitate a UserId / primary email). You would need to use `Get-GSUserList -Query $query` to do what you're looking to do (but it's 100% doable). You'll need to follow Google's User Search syntax for this: https://developers.google.com/admin-sdk/directory/v1/guides/search-users

Here's an example that I just tested with:

```powershell
Get-GSUserList -Query "name='Nate Ferrell'"
```

That all being said, v2.0.0 of PSGSuite allows you to leverage Get-GSUser as a one-stop-shop to provide a level of parity with `Get-ADUser -Filter $filter` if you're familiar with searching for users. Quick example of how this would be done a little closer to expected syntax with the new version:

```powershell
Get-GSUser -Filter "name -eq 'Nate Ferrell'"
```


Cheers!

- Nate

**Comment by cooper** [comment]
Great, thanks for the info.

**Comment by cooper** [comment]
In your example, for Get-GSUserList, how can I query a user by a variable first and last name that might contain apostrophes/single quotes?

**Comment by scrthq** [comment]
As Google requires string search values to be wrapped in single quotes/apostrophes, you need to escape any apostrophes in your search string with a backslash. You would need to do string replacement in line if you're doing it programmatically to account for this

```powershell
# Searching for someone with the exact name "John O'Neal"
$name = "John O'Neal"
Get-GSUserList -Query "name='$($name.Replace("'","\'"))'"
```

**Comment by cooper** [comment]
Thank you for that. I decided it was faster to download the entire user list at the start of the script and use something like:
```powershell
$GSAccount = $googleAccounts | Where-Object { $_.name.fullName -eq $stud.Display }
```
