### ISSUE TITLE
How to get list of groups for a user?

### ISSUE THREAD

**Issue by cooper** [scrthq/PSGSuite#11]
Is there an easy way to get a list of groups to which a user belongs? My script uses job title/other fields in an external source to determine the appropriate groups for the user, then add/remove the user from the appropriate groups.

**Comment by scrthq** [comment]
Yup! You will want to use the `-Where_IsAMember` parameter on `Get-GSGroupList` and pass the target's email address as the value, i.e.:

```
Get-GSGroupList -Where_IsAMember "cooper@domain.com"
```

**Comment by cooper** [comment]
Thank you for the quick reply. This works, but it slows down the processing quite a bit. Do you know of a way to download the entire group membership record in one request and then check against it?

**Comment by scrthq** [comment]
There's no way to do that unfortunately (limitation of Google's API's). The only way to go about pulling every group's member list would be to pull the list of groups and loop through them all, pulling the member list for each. Depending on the amount of users and groups, this way could be faster than pulling the `Where_IsAMember` for each user.

I do something similar in my org with just the in-scope groups that need to be synced (about 60-70 groups); I'll pull the memberlist for the group and generate the list of users that should be in it (i.e. pull AD group membership or reference a user database for an application), then I'll compare the two and adjust the group membership list to match the user list. Not the most ideal situation, but it's the best way that I've found to work around the limitations placed by Google's API.

Maybe one day they'll include a Members and MemberOf property on the group itself, but that's just a hope at this point.

**Comment by cooper** [comment]
I understand. I will fetch the list of groups and then the members of each group. This would definitely be much quicker for my purposes than a separate request for each user. We have about 1,000 users but only a handful of groups. Thank you!

**Comment by scrthq** [comment]
Perfect then!

No problem!
