### ISSUE TITLE
[Feature Request] Calendar event reminders

### ISSUE THREAD

**Issue by Foggy2** [scrthq/PSGSuite#111]
First of all I want to say thanks for all the work on this easy to use module. It has been very useful so far in helping us develop some automation in our G-Suite deployment.

I am currently working on a project where I am exploring the ability for us to automatically publish student timetables to their Google Calendar.

From my investigations so far this can be done quite easily with the New-GSCalendarEvent function. My testing so far shows this works well but the events that are created with the function have an event reminder by default.

For our purposes of publishing a full timetable for all users it wouldn't be well received if all of the events triggered a reminder. So I would like to suggest that support be added for defining the event reminders via the New-GSCalendarEvent and Update-GSCalendarEvent functions.

Thanks!

**Comment by scrthq** [comment]
Hey @Foggy2 - Thanks for sending over the feature request! Looking at the Calendar API now and this doesn't look too difficult to implement =]

Just to confirm, the Calendar Events you're creating are picking up the default reminder setting for the calendar they're being added to, correct? And you'd like to be able to break that inheritance so that no reminders are attached to the event when you create them? 

Also, what about the initial email sent to invitees when an event is created?

**Comment by scrthq** [comment]
@Foggy2 - Did some testing and just deployed [v2.18.1](https://www.powershellgallery.com/packages/PSGSuite/2.18.1) to the PowerShell Gallery containing this update 😄 

Both `New-GSCalendarEvent` and `Update-GSCalendarEvent` now have a `DisableReminder` switch parameter. Pass it and it will prevent inheritance of reminders from the Calendar that the event is on.

Try it out and let me know how it works for you!

**Comment by Foggy2** [comment]
@scrthq - Thanks for the speedy response! This is exactly what I was looking for.

The default reminders on our calendars seem to be 10 minutes so with the new switch `-DisableReminder` I can set no reminder inheritance for the event.

I have just done a quick test and it looks like no reminders were set when using the switch.

> Also, what about the initial email sent to invitees when an event is created?
Good question. For now my use case is not creating meeting events but just adding events to individual calendars. So this isn't a huge concern of mine. Personally though I would see firing off an email as being a good thing but as with anything I am sure there would be instances where not having the email automatically send would be preferred.

My original request is resolved so I am happy for you to close the issue once you are happy.

Thanks again!

**Comment by scrthq** [comment]
Awesome! Glad it's working as needed! Closing this out, cheers! 🍻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
