### ISSUE TITLE
Error when using Get-GSStudentGuardianInvitation

### ISSUE THREAD

**Issue by Foggy2** [scrthq/PSGSuite#117]
Using v2.19.0 the `Get-GSStudentGuardianInvitation` command fails.

![image](https://user-images.githubusercontent.com/23325075/48742032-2b044e80-ecad-11e8-8c48-ef176d401a93.png)

**Comment by scrthq** [comment]
@Foggy2 - v2.20.0 out now with the fix. Enjoy!
