### ISSUE TITLE
Issue running script with PSGSuite from remote computer.

### ISSUE THREAD

**Issue by cheetahwilly** [scrthq/PSGSuite#119]
I have created a script to automate my user creation process.  This script works perfectly fine when I execute it on the server that is hosting it.  The problem is that I am gathering my information on a form from another server, then executing the script from this server (via C# built into the application) with the required parameters.

At first, I was getting the following error in Event Viewer:

The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID
{D63B10C5-BB46-4990-A94F-E40B9D520160}
and APPID
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
to the user DOMAIN/USERNAME SID (S-1-5-21-2164478548-1640378833-2111261494-1103) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

I have since resolved this issue by assigning the appropriate permissions via Grant-DCOMPermission.

My other modules work fine (Active Directory Module & gShell which I am trying to replace).  The issue is when I get to the PSGSuite commands. 

Here are the following errors I am getting when executing via Invoke-Command (using Credssp):

A positional parameter cannot be found that accepts argument 'GROUP@DOMAIN.COM'.
    + CategoryInfo          : InvalidArgument: (:) [Add-Content], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.AddContentCommand
    + PSComputerName        : SERVERNAME

The value supplied is not valid, or the property is read-only. Change the value, and then try again.
    + CategoryInfo          : InvalidData: (:) [New-GoogleService], Exception
    + FullyQualifiedErrorId : SetValueException,New-GoogleService
    + PSComputerName        : SERVERNAME

The value supplied is not valid, or the property is read-only. Change the value, and then try again.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-GSGroupMember
    + PSComputerName        : SERVERNAME

I see that this script is indeed running as the correct user, but I also get the same errors when I don't run the script under PowerShell as administrator.

What exactly is preventing PSGSuite from running from ServerRemoteHost?  Can I do anything to allow this?

 - OS:  Server 2016 Datacenter
 - PowerShell Version:  5.1.14292
 - PSGSuite Version: 2.20.20 (PowerShell Gallary)

**Comment by cheetahwilly** [comment]
New look this morning.. May have Solved it. Will follow up if actually PSGSuite.

**Comment by scrthq** [comment]
@cheetahwilly - no worries! The only thing that I can think of would be oddities when decrypting the config due to DPAPI issues over WinRM, but I'm able to decrypt my remote config fine over WinRM (Kerberos on my end, not CredSSP, but I feel like there would be inherently _more_ issues with Kerberos than CredSSP for DPAPI interaction)

Let me know once you've found the fix, if possible! It could prove useful for anyone following up here 💪

**Comment by cheetahwilly** [comment]
Appears to be something odd with my Compare-Object looping.  I am comparing what the user already has from SQL and determining if I need to add/remove the group.   I am not really sure if this is PSGSuite or not.

$emailcompare = Compare-Object $oldGArray $emailArray
foreach ($email in $emailcompare)
   {
   $groupname = ""
   $groupname = $email.InputObject+"@DOMAIN"
   if ($email.SideIndicator -eq "=>")
   {
    Write-Host "Add-GSGroupMember" $groupname "-Member" $UserName"@DOMAIN"
    Add-GSGroupMember -Identity "$groupname" -Member $UserName"@DOMAIN"
    }
        else{
        Write-Host "groupname" $groupname "-" $email.InputObject "-" $($email.InputObject)
        Write-Host "Test Command: Remove-GSGroupMember -Identity" $($email.InputObject) "-Member" $UserName" -Confirm:$false"
        Remove-GSGroupMember -Identity "$groupname" -Member $UserName -Confirm:$false
    }

The value supplied is not valid, or the property is read-only. Change the value, and then try again.
    + CategoryInfo          : InvalidData: (:) [New-GoogleService], Exception
    + FullyQualifiedErrorId : SetValueException,New-GoogleService
    + PSComputerName        : SERVERNAME

You cannot call a method on a null-valued expression.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Remove-GSGroupMember
    + PSComputerName        : SERVERNANE

**Comment by scrthq** [comment]
Yeahhhhh, looks like Compare-Object's formatting may be wreaking havoc. Are you just using this to sync Google Group members against a list of email addresses, where they're removed from the group if they're no longer in the list and added if they are and not already in the group?

This sounds like a good time to pick back up the Sync function I was working on, if so. Perfect use case for it.

**Comment by cheetahwilly** [comment]
This is an action for one user against a list of different groups.    I have a different script the grabs all of the gSuite information that I need and dumps it into a SQL DB, works great.

I then have an "Update user form" for management that populates a form with the groups they already have.   They then update this form and I send the selected groups to my script which determines which ones to add/remove.

**Comment by scrthq** [comment]
Nice! Have you looked at `Add-GSPrincipalGroupMembership` & `Remove-GSPrincipalGroupMembership` for handling the "one user, multi group" scenarios? Coming from an ActiveDirectory module background myself, I designed those functions as convenience wrappers to do the same as `Add-ADPrincipalGroupMembership` does in comparison to `Add-ADGroupMember`, the goal being feature parity (as much as possible) between the AD cmdlets and PSGSuite functions.

Here's how you would do what you're looking for with just 2 commands:

```powershell
Add-GSPrincipalGroupMembership -Identity "$($UserName)@Domain" -MemberOf $($emailArray | Where-Object {$oldGArray -notcontains $_})
Remove-GSPrincipalGroupMembership -Identity "$($UserName)@Domain" -MemberOf $($oldGArray | Where-Object {$emailArray -notcontains $_})
```

**Comment by scrthq** [comment]
Also worth noting that most, if not all, PSGSuite commands allow you to include just the email name part (i.e. `user.name`) instead of the full email (`user.name@domain.com`) if the domain part is the same as what's stored in your PSGSuite Config as the domain.

**Comment by cheetahwilly** [comment]
Ok strange.   I wrote up a small test script to use your Add-GSPrincipalGroupMembership.  

(Incoming groups come at group1;group2;group3)

$emailGroups = $GroupList.ToLower() -replace ';',','
$array1 = $emailGroups -split ','

#Puts all groups in a string like "group1","group2","group3"
$a3 = '"{0}"' -f ($array1 -join '","')

write-host "Array:" $a3

Write-Host "Add-GSPrincipalGroupMembership -Identity USERNAME@ci.galesburg.il.us -MemberOf" $a3
Add-GSPrincipalGroupMembership -Identity USERNAME@ci.galesburg.il.us -MemberOf $a3

I get these errors when executing remotely:

Exception calling "Execute" with "0" argument(s): "Google.Apis.Requests.RequestError
Resource Not Found: groupKey [404]
Errors [
    Message[Resource Not Found: groupKey] Location[ - ] Reason[notFound] Domain[global]
]
"
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GSGroup
    + PSComputerName        : SERVERNAME

Exception calling "Execute" with "0" argument(s): "Parameter validation failed for "groupKey""
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-GSPrincipalGroupMembership
    + PSComputerName        : SERVERNAME


Execute the exact same command on the local machine that is displayed in Write-Host and it works perfectly.

**Comment by scrthq** [comment]
Really strange regarding the different behavior on remote vs local. Is there a PSVersion difference between the two?

Also worth noting that you're concatenating the array into a single string, which is going to have some wonky effects since it's considering the concatenated string as a single group to add the user to (which is why you're getting that error, since that is an invalid email address [`groupKey`]). You're best off passing `$array1` as the value to `-MemberOf` since the MemberOf parameter accepts an array of strings.

**Comment by cheetahwilly** [comment]
Yeah I tried with the array first and had issues so I decided to get it formatted like Example 1 at:
https://github.com/scrthq/PSGSuite/wiki/Add-GSPrincipalGroupMembership

The version is slightly different.  Let me update it and see if I can reproduce.

**Comment by cheetahwilly** [comment]
SMH.  So, all problems were resolved (remotely) after removing a left over Import-Module PSGSuite at the beginning of the script.

Existing code works fine, but I implemented what you suggested.   Thanks for your help.

**Comment by scrthq** [comment]
Glad it was something simple! The most facepalming fixes can be the most relieving.

Happy to help! Let me know if anything else pops up!
