### ISSUE TITLE
Possibility to approve mobile device

### ISSUE THREAD

**Issue by lucafabbri365** [scrthq/PSGSuite#120]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to retrieve mobile device from Device Management (Remove-GSMobileDevice) or retrieve the list of Mobile Devices registered for the user's account (Get-GSMobileDevice)

**Describe the solution you'd like**
The possibility to approve mobile device (Update-GSMobileDevice)

**Comment by scrthq** [comment]
hey @lucafabbri365 - Checking this out! Thanks, Luca!

**Comment by scrthq** [comment]
Hey @lucafabbri365 - This has been released as `Update-GSMobileDevice` in v2.20.2! Update when you can, cheers!

**Comment by lucafabbri365** [comment]
> Hey @lucafabbri365 - This has been released as `Update-GSMobileDevice` in v2.20.2! Update when you can, cheers!

Thank you very much @scrthq !! I started using it.

Bye,
Luca

**Comment by scrthq** [comment]
Cheers!
