### ISSUE TITLE
Feature request - Additional group support

### ISSUE THREAD

**Issue by n-searle** [scrthq/PSGSuite#121]
Hiya Nate,

Is it possible to add functions such as Set-GSGroupMember allowing us to change a members role in a group between member/manager/owner  and also set their delivery preferences allmail/nomail/daily/digest  in a similar manner to GAM?

Cheers,
Neil

**Comment by scrthq** [comment]
Hey @n-searle! Checking this out, thanks for sending the feature request over!

**Comment by scrthq** [comment]
Added in `Update-GSGroupMember` to v2.20.1, available now on the PSGallery! Thanks again for submitting the feature request, @n-searle!
