### ISSUE TITLE
Wrong values case for "Fields" parameter in Get-GSSheetInfo wiki

### ISSUE THREAD

**Issue by lucafabbri365** [scrthq/PSGSuite#128]
**Describe the bug**
Wrong values case for _Fields_ parameter in **Get-GSSheetInfo** wiki.

**To Reproduce**
[Get-GSSheetInfo](https://github.com/scrthq/PSGSuite/wiki/Get-GSSheetInfo#-fields)

**Expected behavior**
Fields must be written in lower case:

- "namedranges"
- "properties"
- "sheets"
- "spreadsheetid"

**Comment by scrthq** [comment]
Thanks, Luca!

This is just a documentation fix; the actual ValidateSet options are in camelCase as they should be; specifically camelCase, not all lowercase (this will actually fail in the same way that the parameter help's TitleCase options do for Fields that are multiple words like `namedRanges` or `spreadsheetId`).

I could also force case conversion in the function body, but using the options in ValidateSet as they are works without issue so long as they aren't manually typed with different casing. You can tab complete through the available fields though when choosing a value for that parameter.

**Comment by scrthq** [comment]
This will be fixed up in the upcoming release!

**Comment by scrthq** [comment]
@lucafabbri365 - fix has been released as of now in v2.21.0! Check it out when you can!

**Comment by lucafabbri365** [comment]
Hello Nate,
you are simply great !!!

Thank you,
Luca
