### ISSUE TITLE
Add Support for UserRelations

### ISSUE THREAD

**Issue by mattwoolnough** [scrthq/PSGSuite#129]
Add Support for UserRelation

https://developers.google.com/resources/api-libraries/documentation/admin/directory_v1/java/latest/com/google/api/services/admin/directory/model/class-use/UserRelation.html

**Comment by mattwoolnough** [comment]
Looking for some ideas on how to implement the deletion of relations. 

To remove a relation via the HTTP API, it seems the only way is to PUT an empty JSON Object
{
 "relations": [{}]  
}

This results in the following value in relations:
"relations": [{
    "type": "custom"
 }],

**Comment by scrthq** [comment]
@mattwoolnough - I believe I implemented something on another function for a similar purpose, let me try and dig it out. IIRC, you need to set the value as an empty generic list if the parameter is used in `$PSBoundParameters` but is `$null`. Give me a bit =]

**Comment by mattwoolnough** [comment]
Sorry, to delete the JSON below is required. Did you happen to find the code you were thinking of?

```
{
 "relations": null  
}

```

**Comment by scrthq** [comment]
@mattwoolnough - still hunting for it, but I know that the .NET SDK regards sending `$null` as not being sent at all, not a deliberate `$null`. I see your PR as well. I've been pretty slammed with normal work + family + holidays, so my sincere apologies for not being as quick on the response and deploying your PR's as well! Working on pulling in a few additional things into the next release as well if possible, so it's been a battle.

**Comment by scrthq** [comment]
have you tried just sending `$null` as the value for that property with a call to `Update-GSUser`? The section in the `switch` statement should still create a blank list and submit that, if I remember correctly.

**Comment by scrthq** [comment]
disregard, just tested and that didn't do anything (at least for `Relations` anyway)

**Comment by scrthq** [comment]
Alright, found the bit of code that I was thinking of similar to removing values:

https://github.com/scrthq/PSGSuite/issues/16#issuecomment-385137905

Did some testing based on this and the following works (although is does leave a null reference for the Relation value when pulling the user information via API):

***

Before (view from Admin console and view from `$user.Relations`):

![image](https://user-images.githubusercontent.com/12724445/50237737-3ec1d400-0383-11e9-94ac-203b272253d0.png)

![image](https://user-images.githubusercontent.com/12724445/50237795-62851a00-0383-11e9-9835-046a26a70cf3.png)

***

After:

![image](https://user-images.githubusercontent.com/12724445/50237839-7df02500-0383-11e9-8bba-b26f96d4961c.png)

![image](https://user-images.githubusercontent.com/12724445/50237859-89435080-0383-11e9-9964-f6389fc49a3b.png)

**Comment by scrthq** [comment]
alright, that's going to be the only applicable approach for clearing the value of a **single** relation/phone/etc. I've looked at your code in your PR for `Remove-GSUserPhone` and have applied something more widespread directly on `Update-GSUser` to allow passing `$null` as the value to clear out all entries for that property type.

Example in use:

```powershell
Update-GSUser -User $user.PrimaryEmail -Relations $null
```

![image](https://user-images.githubusercontent.com/12724445/50240418-5e102f80-038a-11e9-8e10-86aa828fec34.png)

**Comment by scrthq** [comment]
@mattwoolnough - Thanks for the contributions around this! UserRelation support is out now in v2.21.0. I've also included the updated logic for clearing out `ExternalIds`, `Phones`, `Relations`, and `Organizations` into `Update-GSUser` via passing `$null` as the value for those parameters. As noted, if you need to clear out a specific item, just pass `$null` for the value of the item on the appropriate helper function.

Let me know if you have any questions regarding this!
