### ISSUE TITLE
Issue with Add-GSUserExternalId

### ISSUE THREAD

**Issue by arnoutvandervorst** [scrthq/PSGSuite#14]
$extId = Add-GSUserExternalId -Type Login_Id -Value jsmith2

Response:
Add-GSUserExternalId : Cannot validate argument on parameter 'Value'. The argument "jsmith2" does not belong to the set "account,custom,customer,login_id,network,organization" specified by the ValidateSet attribute
. Supply an argument that is in the set and then try the command again.

**Comment by scrthq** [comment]
Thanks, Arnout! 2.0.2 getting built shortly with the fix. I appreciate you letting me know!

**Comment by scrthq** [comment]
2.0.2 deployed!

![conemu64_2018-02-06_08-45-26](https://user-images.githubusercontent.com/12724445/35871825-182ff91e-0b1a-11e8-8f05-4c73de114b3e.png)

**Comment by arnoutvandervorst** [comment]
Cheers!
