### ISSUE TITLE
Non SuperAdmin account Directory API Access

### ISSUE THREAD

**Issue by worldtraveler123** [scrthq/PSGSuite#142]
Hello,

I am looking to roll out the capability to create new resource rooms for other members of my team.  Currently, we have standard user accounts provisioned and I'd like for them to be able to create new resources within the company.  

It looks like the New-GSResource cmdlet requires access to the Directory API.  Is there any way for a standard user account to create new resources?  Or is it required that they be a Super Admin?

Any and all help would be greatly appreciated here!

Thanks.

**Comment by scrthq** [comment]
Hey @worldtraveler123 - You can try testing out a delegated admin role, but I don't believe you can delegate API access for Resource Management via Admin SDK specifically for delegated admins.

My best suggestion would be to create a configuration using a service account with the necessary permissions and supply that along with PSGSuite.  
* This can be risky without implementing additional guards if the account has full SuperAdmin permissions.
* The risk can be lowered a bit if you build a service account that only has the necessary API's enabled and scopes permitted. If you're going this route, I highly recommend tapering the permissions level there.

**Comment by worldtraveler123** [comment]
Thank you for the guidance @scrthq !  I was able to get this working...

- Create SuperAdmin service account in the console (solely for this purpose).
- Run through the initial setup instructions you have in the Wiki.
- Create ServiceAccount in the developers console using the SuperAdmin account. 
- Set the consent screen to the SuperAdmin account address.
- In the admin console, allow API access to the following scope: https://www.googleapis.com/auth/admin.directory.resource.calendar 
- Grant access to the P12 key for your users as well as the 
- Run the Set-PSGSuiteConfig cmdlet using the appropriate parameters (P12Key, AppEmail, AdminEmail and ServiceAccountClientID).
- Test away!

I can confirm this process works and I plan to distribute instructions to my teammates for creating new resource rooms (I also have a script that leverages New-GSResource).

PSGSuite has been immensely helpful in managing our G Suite domain, so many thanks Nate!

**Comment by scrthq** [comment]
hey @worldtraveler123 - That's awesome to hear! The easiest way to restrict the capabilities of that account (or at least the key distributed out) is to limit the enabled API's for that project in the Developer's Console to only the `Admin SDK` as well as limit the scope that you provide Client API access to only `https://www.googleapis.com/auth/admin.directory.resource.calendar`. This will ensure that others can't look at your underlying code and start pulling Gmail messages for users or manipulating Drive files.

Also worth noting that I recently added the ability to export PSGSuite configurations to a portable JSON file using the `Export-PSGSuiteConfig` command. You can use this JSON file in combination with `Import-PSGSuiteConfig` at the top of your script to package it up without worrying about the default encryption that accompanies the standard config (if preferred).

Let me know if you have any additional questions!
