### ISSUE TITLE
[Feature Request] Manage signatures in Gmail

### ISSUE THREAD

**Issue by scrthq** [scrthq/PSGSuite#152]
`@Jonas` on the SCRT HQ Slack requested the ability to manage signatures in Gmail to replicate the existing GAM command `gam user $useremail signature file $htmlfilepath charset utf16 html`

**Comment by phatmandrake** [comment]
I'd be able to completely divest from GAM if this comes about. 10/10

**Comment by scrthq** [comment]
![image](https://user-images.githubusercontent.com/12724445/53466369-44890500-3a17-11e9-856f-2e8d3ff6e489.png)

Working great in Dev! @phatmandrake 

Going to add in a more direct wrapper function `Update-GSGmailSignature` since I feel this is going to be a lot more commonly used than the rest of the SendAs settings.

Hoping to have these and a number of other new features and bug fixes out this weekend!

**Comment by scrthq** [comment]
![image](https://user-images.githubusercontent.com/12724445/53468997-ef062580-3a21-11e9-8861-681ca642b71a.png)

Wrapper function added in with some cool bells and whistles (read from local file and/or as plain text) =]

**Comment by scrthq** [comment]
Out now on the PS Gallery in v2.23.0! Get it while it's hot =]
