### ISSUE TITLE
Update Wiki Initial Setup

### ISSUE THREAD

**Issue by phatmandrake** [scrthq/PSGSuite#155]
The UI has changed. For step 5

> CHECK the box to Enable G Suite Domain-wide Delegation

The checkbox is no longer accessible at this step. You now must select "Done", which will download the .P12 file. You are then returned to the Service Accounts page. To enable G Suite Domain-Wide Delegation select edit under the actions menu (3 vertical dots). Then click on "Show Domain Wide-delegation", and check the box to Enable G Suite Domain-wide Delegation.

The interface has changed substantially so this part could get confusing if you're unfamiliar with the process.

**Comment by scrthq** [comment]
Wiki has been updated, let me know what you think!
