### ISSUE TITLE
Commands are not working

### ISSUE THREAD

**Issue by grunger-deloitte-com** [scrthq/PSGSuite#157]
I followed all instructions. I am getting the following errors.

Get-GSUserList -domain 'something.com' -verbose
VERBOSE: Building ServiceAccountCredential from P12Key as user 'abc123@something.com'
New-Object : Cannot find an overload for "DirectoryService" and the argument count: "1".
At C:\Program Files\WindowsPowerShell\Modules\PSGSuite\2.23.0\PSGSuite.psm1:1442 char:9
+         New-Object "$ServiceType" (New-Object 'Google.Apis.Services.B ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
Get-GSUserList : You cannot call a method on a null-valued expression.
At line:1 char:1
+ Get-GSUserList -domain 'something.com' -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GSUser

PS C:\Users\grunger> Get-GSUserLicense
Get-GSUserLicense : Cannot find an overload for "LicensingService" and the argument count: "1".
At line:1 char:1
+ Get-GSUserLicense
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GSUserLicense

**Comment by scrthq** [comment]
Hi @grunger-deloitte-com - Sounds like something may be off with your config.

Does the following return `False` or `True` when you run it?

```powershell
Test-Path (Show-PSGSuiteConfig).P12KeyPath
```

**Comment by scrthq** [comment]
also, did you run `Import-Module PSGSuite` after installing or start running commands directly? Could you try the following?
1. Restart your PowerShell session
2. `Import-Module PSGSuite`
3. `Get-GSUser`

**Comment by grunger-deloitte-com** [comment]
The quick response is very appreciated Nate!

PS C:\Users\grunger> Test-Path (Show-PSGSuiteConfig).P12KeyPath
True

I changed the values. I did install modules. Command are showing up in the command window
Intellisense is also working.
Install-Module -Name PSGSuite

$P12KeyPath = 'C:\Users\something\rapid-pivot-111111-fe58f8bbff9e.p12'
$AppEmail = 'something@rapid-pivot-11111.iam.gserviceaccount.com'
$AdminEmail = 'abc123@something.com'
$CustomerID = ''
$Domain = ‘something.com'
$Preference = 'Domain'
$ServiceAccountClientID = '1011111111111111111'


#Set-PSGSuiteConfig -ConfigName MyConfig -SetAsDefaultConfig -P12KeyPath $P12KeyPath -AppEmail $AppEmail -AdminEmail $AdminEmail -CustomerID $CustomerID -Domain $Domain -Preference $Preference -ServiceAccountClientID $ServiceAccountClientID
Set-PSGSuiteConfig -ConfigName MyConfig -SetAsDefaultConfig -P12KeyPath $P12KeyPath -AppEmail $AppEmail -AdminEmail $AdminEmail -Domain $Domain -Preference $Preference -ServiceAccountClientID $ServiceAccountClientID

**Comment by scrthq** [comment]
got it! can you try explicitly _`Import`ing_ the module before the commands? I see your call to Install-Module, but no Import-Module

For some background, running the commands without explicitly importing the module first can possibly skip logic that takes place on the PSM1 file itself when you import it.

**Comment by grunger-deloitte-com** [comment]
That worked! 😊 Thanks very much!

**Comment by scrthq** [comment]
Awesome! You bet!

Checking out the docs and seeing where I can update to make that clearer. Thanks for opening this up! Let me know if you have any questions, comments or concerns!

**Comment by grunger-deloitte-com** [comment]
Thanks brother

**Comment by scrthq** [comment]
FYI - Cleaned up your responses @grunger-deloitte-com since it had your email signature / details included. Cheers!
