### ISSUE TITLE
Get-GSUser Wildcard Search

### ISSUE THREAD

**Issue by IronKane2** [scrthq/PSGSuite#161]
Can Get-GSUser -filter do a wildcard search on PrimaryEmail or User?  Student email accounts are their initials+ID.

Sometimes student registration is incorrect and there is a name change and the account script ends up creating a second account.

**Comment by scrthq** [comment]
Hey @IronKane2 - You can leverage the `-Filter` parameter and Google's user search syntax for that actually: https://developers.google.com/admin-sdk/directory/v1/guides/search-users

I've added some conversion helpers to translate between PowerShell filter syntax and Google's, but it's a best effort and your mileage may vary. If you use `-Verbose` with Get-GSUser, it will print out the filter that it's trying to use for reference (useful when you 

I've also added some "familiar" additional parameters to try and make `Get-GSUser` behave like `Get-ADUser` as much as possible, i.e. `SearchBase` and `SearchScope`.

Here are some examples of search options:

1. Search for a user by email - exact match (`-eq`):

    > Google search syntax

    ```powershell
    Get-GSUser -Filter "email='john.doe@domain.com'" -Verbose
    ```

    > PowerShell syntax

    ```powershell
    Get-GSUser -Filter "email -eq 'john.doe@domain.com'" -Verbose
    ```

2. Search for a user by email - partial/wildcard match (`-like`):

    **This is a PREFIX match, not a true wildcard match. See [Google's Search Users doc](https://developers.google.com/admin-sdk/directory/v1/guides/search-users) for more information** 

    > Google search syntax

    ```powershell
    Get-GSUser -Filter "email:'john.d*'" -Verbose
    ```

    > PowerShell syntax

    ```powershell
    Get-GSUser -Filter "email -like 'john.d*'" -Verbose
    ```

3. Search for users under a given Organizational Unit:

    > Google search syntax

    ```powershell
    Get-GSUser -Filter "orgUnitPath='/Core'" -Verbose
    ```

    > PowerShell syntax using Filter only

    ```powershell
    Get-GSUser -Filter "orgUnitPath -eq '/Core'" -Verbose
    ```

    > PowerShell syntax using SearchBase + SearchScope + `Filter *`

    ```powershell
    Get-GSUser -Filter * -SearchBase /Core -SearchScope SubTree -Verbose
    ```

**Comment by IronKane2** [comment]
Thank you!  This is what I was looking for.   I did look at that Google Doc before I posted this, but I didn't know how it applied to your cmdlet.

**Comment by scrthq** [comment]
You bet! I need to update the function help as well to cover something that deep as well. Here's the current help contents for the `Filter` parameter:

```powershell
> Get-Help Get-GSUser -Parameter Filter

-Filter <String[]>
    Query string for searching user fields

    For more information on constructing user queries, see: https://developers.google.com/admin-sdk/directory/v1/guides/search-users

    PowerShell filter syntax here is supported as "best effort". Please use Google's filter operators and syntax to ensure best results

    Required?                    false
    Position?                    named
    Default value
    Accept pipeline input?       false
    Accept wildcard characters?  false
```

**Comment by IronKane2** [comment]
Get-GSUser -Filter "email -like '*71084*'" -Verbose
and
Get-GSUser -Filter "email -like '*71084'" -Verbose
doesn't work.  Can't do a preceding wildcard?

**Comment by scrthq** [comment]
You cannot, it's a prefix match only per Google's design 😢 

![image](https://user-images.githubusercontent.com/12724445/53977993-d2c45180-40cf-11e9-9821-1e753029568d.png)

![image](https://user-images.githubusercontent.com/12724445/53978028-deb01380-40cf-11e9-91c7-fea9a32f78cd.png)

**Comment by IronKane2** [comment]
That's what I thought.  My workaround is in addition to loading users into a hash with Sync-GSUserCache, I also am loading an array with Get-GSUser and do a pipeline filter.  Since this only occurs occasionally, the performance hit is small other than the additional 60 seconds needed to load the array with 9,000 students.

Thanks for the assistance.

**Comment by scrthq** [comment]
You can do the following to lookup against your UserCache pretty quickly with actual Where-Object access:

```powershell
$filter = "*71084"
$domain = (Show-PSGSuiteConfig).Domain
($global:GSUserCache.Keys | Where-Object {$_ -like "*$filter@$domain"}) | ForEach-Object {
    $global:GSUserCache[$_]
}
```

**Comment by IronKane2** [comment]
I got too focused on one direction.  I should have thought of that.

Your answer sparked another question.
Since I really don't want to type or paste $global:GSUserCache all the time, which is better:
$GUsers = Sync-GSUserCache -PassThru  -Verbose 
or 
$GUsers = $global:GSUserCache ?

I've been using the former.  Since I have to call the Sync in either case, does it matter?

**Comment by scrthq** [comment]
So it's completely up to you! `Sync-GSUserCache` fills out `$global:GSUserCache`, so you could even just do the following:

```powershell
# Fill out $global:GSUserCache by running Sync-GSUserCache (no need to store the results in a local variable)
Sync-GSUserCache -Verbose

# Access the cache immediately after
$global:GSUserCache["user1@domain.com"]
```

The `-PassThru` option is there for clarity, since it's very visible that you're storing the output of `Sync-GSUserCache` in a clear variable for anyone else reading a script you wrote when including `$GUsers = Sync-GSUserCache -PassThru -Verbose` compared to `Sync-GSUserCache -Verbose` with the background understanding that the global var is being filled.
