### ISSUE TITLE
Create a session and pass it to commands in addition to ad-hoc sessions

### ISSUE THREAD

**Issue by n-searle** [scrthq/PSGSuite#162]
Hi Nate,

I have several scripts that perform the same command on multiple users which it looks like I can do by piping them into the PSGSuite functions as the session is created in the begin block.  However I also want to provide feedback during the process and also to allow the user to make choices sometimes on what to do.  At the moment this means I have to call the command individually for each user meaning a new session is created each time which significantly slows some of my operations on large numbers of users.

What I would like to do is to be able to create a session and store it in a variable and pass it to the functions I am using so they do not need to make their own.

Is that something you reckon you could implement?

Cheers,
Neil

**Comment by scrthq** [comment]
Hey @n-searle - Doing that may be a bit complex depending on what commands you're expecting to run within that same Service object. 

What API's/functions are you using in that process? I.e. are you running a bunch of User commands (i.e. Update-GSUser), Gmail, Drive, or a mix?

**Comment by n-searle** [comment]
Hey,

Currently it is mainly User and Group commands which looking at your code appear to use the same Service type.

I see where it could get more complex as I now see there are different session types.  A couple of solutions I can think of:

Different services could use a differently typed object ensuring the functions only accept the correct type of service object.  ie new-gsusersession / new-gsdrivesession.  I don't think this would be too bad.

A more complete but Powershell v5 solution could be to use a single class as a session manager and have it manage the sessions that are requested of it.  It could house a session variable for each service type and open a session when it is requested by the function it is passed by reference to.  User based functions could call a class method such as $MySessionClass.getUserSession and have it return the user based session object and similar for drive etc. $MySessionClass.getDriveSession.

**Comment by scrthq** [comment]
@n-searle 	Got it!! I think I have an idea on how to solve this behind the scenes actually... I'm working on building/testing a caching process for the GoogleService object; when a new service is requested, it will check the cache for any existing Service objects that match the same criteria (token not expire and Service Type, AdminEmail and Scope(s) match) and only create a new one if needed, otherwise it returns the match from the cache.

Adjusting the output type is tricky since Google's .NET SDK is pretty strongly typed and PS Classes are out of the question while still supporting PS4+.

---------------------

I think the session manager idea you had is more or less the same idea that I have with the service cache, just building it into the existing New-GoogleService function that everything is already using

**Comment by n-searle** [comment]
Hi Nate,

Yep that sounds great and was pretty much what I was thinking, I was hoping you would have something in mind to avoid the classes as I guessed you would want to keep PS4 compatibility :)

Cheers

**Comment by scrthq** [comment]
Got the session cache working well! Also added in a new function to see the current cache, `Get-PSGSuiteServiceCache`. Here's it in action, demonstrated by...
1. running `Get-GSUser` after importing the module (creates the Service new)
    * Run time: `0:00:00.8000`
2. running `Get-PSGSuiteServiceCache` to view the current cache contents
3. running `Get-GSUser` again, this time using the existing matching Service from the cache
    * Run time: `0:00:00.2499` (about 1/3 the speed of the initial service creation)

![image](https://user-images.githubusercontent.com/12724445/54658650-82b89800-4a9c-11e9-9001-38e0a2cb1bfd.png)

***

Now I'm just waiting an hour to see how the existing service handles expired tokens. I'm expecting it to refresh it without issue, but we shall see. If all goes well, I should have this deployed tonight or tomorrow!

**Comment by scrthq** [comment]
Confirmed that it handles the token refresh internally in the Google .NET SDK without any extra coding needed, this is looking pretty solid currently =]. Fantastic idea overall!

**Comment by scrthq** [comment]
To cut down on verbose noisiness, the following verbose output is set:
1. New Service created = `Building ServiceAccountCredential from....`
2. First use of existing Service = `Using matching cached service for user....`
3. Re-use of existing Service = No verbose output (helps cut down on pipeline verbosity where service re-use is expected)

![image](https://user-images.githubusercontent.com/12724445/54660463-8d772b00-4aa4-11e9-904f-92cacdaf6602.png)

**Comment by scrthq** [comment]
Let me know how this works for you! v2.25.0 is on the Gallery now!

**Comment by scrthq** [comment]
hey @n-searle - Just want to say thank you for opening this up. It was a pretty trivial feature to implement, but I'm already personally seeing immense benefits with my own automation leveraging PSGSuite for my org. Pretty great!

**Comment by n-searle** [comment]
Hey Nate,

Yep working great, thanks very much for implementing.  I am glad it's as much use to you as well, feels less like I am burdening you lol :D

Top work!

Cheers

**Comment by scrthq** [comment]
Burden?! I'll take a feature request over a bug any day! 🥇 Definitely a big quality-of-life change, hopefully you're seeing some perf gains on your end also!
