### ISSUE TITLE
[Feature Request] Please add Get-GSCalendar & Remove-GSCalendarACL

### ISSUE THREAD

**Issue by kevinblumenfeld** [scrthq/PSGSuite#163]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem

**Describe the solution you'd like**
Would love to be able to query specific calendars and remove ACL's.  Specifically, “Make changes AND manage sharing” ACL

**Describe alternatives you've considered**
Considered GAM but hey that's not PowerShell and can't accomplish it this way.

**Additional context**
Thank you.  This is specifically what I am running into: https://support.quest.com/on-demand-migration-for-email/kb/111726/shared-calendars-from-google-g-suite-get-migrated-to-office-365-as-a-new-calendar

**Comment by scrthq** [comment]
Thanks, @kevinblumenfeld!!! I'll let you know as soon as I have this out! Shouldn't take long to implement.

**Comment by scrthq** [comment]
`Get-GSCalendar` and `Remove-GSCalendarAcl` added into v2.25.0 along with a number of other improvements!

To do what you're after, I believe this would work for you:

```powershell
$targetUser = 'user@domain.com'
$targetUser = 'user@domain.com'
Get-GSCalendar -User $targetUser | Where-Object {$_.AccessRole -eq 'Owner'} | 
    Get-GSCalendarAcl | Where-Object {$_.Role -eq 'Owner' -and $_.Scope.Value -ne $targetUser} | 
    Remove-GSCalendarAcl -WhatIf
```

This...
1. Gets the calendar list where the `$targetUser` is the `Owner`
2. Gets the ACL rules for each calendar where the rule Role is `Owner` (this equates to Manage Events & Sharing) and the scope of the rule is not the `$targetUser` (here to prevent removal of self or potential errors)
3. Removes the matching rules from the calendars they are on.



Let me know how this works for you! v2.25.0 is on the Gallery now!
