### ISSUE TITLE
update GSuite Phone field 

### ISSUE THREAD

**Issue by indianwind** [scrthq/PSGSuite#166]
i can create Guser with work phone field but can't do update
when i run update-GSUser, it makes phone filed empty.
anything wrong here?

$gphone = Add-GSUserPhone -Type work -Value $phone -Primary
New-GSUser -PrimaryEmail $homepage -GivenName $Firstname -FamilyName $Lastname -Password (ConvertTo-SecureString -String $Password -AsPlainText -Force) -Phones $gphone

$gphone = Add-GSUserPhone -Type work -Value "888" -Primary
Update-GSUser -User "testlastte" -Phones $gphone

tony

**Comment by scrthq** [comment]
Hey Tony - it looks correct from here, let me see if I can replicate and I'll get a fix out asap if so! Will let you know shortly @indianwind 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by indianwind** [comment]
thx so much @scrthq

**Comment by scrthq** [comment]
Here's the issue:

![image](https://user-images.githubusercontent.com/12724445/54968400-92c2f280-4f48-11e9-948a-cd0ab12cb25b.png)


Fix is building now in Azure Pipelines, should be deployed in v2.25.1 within the next 10 minutes or so! I'll comment back here once available on the Gallery 😃

**Comment by indianwind** [comment]
that's fast! genius~
you work for google?

**Comment by scrthq** [comment]
I wish! One day, maybe =]. For now, I'm just a G Suite admin (among many other things) with a passion for PowerShell and building useful tools =]

v2.25.1 available on the Gallery now! Check it out and let me know =]

**Comment by scrthq** [comment]
....Found another unrelated bug ( #167 ), so v2.25.2 is actually building and deploying now. both versions contain your fix though!

**Comment by scrthq** [comment]
Before:

![image](https://user-images.githubusercontent.com/12724445/54969429-10d4c880-4f4c-11e9-876f-5db8cd9646e6.png)

After:

![image](https://user-images.githubusercontent.com/12724445/54969456-2c3fd380-4f4c-11e9-932c-872b71d7b387.png)

**Comment by indianwind** [comment]
thx, that's what i'm checking too!
what do i do to apply the patch?
sorry, my 1st time to apply patch here.
download whole thing or just the files u uploaded? @scrthq

**Comment by scrthq** [comment]
Did you install from the PS Gallery or directly from the repo? If from PSGallery, just run `Update-Module PSGSuite`, if you installed from the Releases on the repo, then you can follow the instructions to download the release and unzip it and all that jazz.

Here's the link to the latest release if that's the route you're going: https://github.com/scrthq/PSGSuite/releases/tag/v2.25.2

**Comment by indianwind** [comment]
download and import.
working like magic! thx @scrthq

**Comment by scrthq** [comment]
You bet!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
