### ISSUE TITLE
Support for User Locations

### ISSUE THREAD

**Issue by gfree23** [scrthq/PSGSuite#168]
It would be great to have support for user locations on the Update-GSUser and New-GSUser.
https://developers.google.com/admin-sdk/directory/v1/reference/users/insert

locations[].area
locations[].buildingId
locations[].customType
locations[].deskCode
locations[].floorName
locations[].floorSection
locations[].type

Thanks!

**Comment by scrthq** [comment]
Hey @gfree23 - I'm on it! Should have this turned around by this weekend, completely makes sense! I'll keep you updated here

**Comment by scrthq** [comment]
Hey @gfree23 - Location support is being deployed in v2.26.0 right now! This will behave identically to ExternalIds/Organizations/Phones in that there is a new Helper function named `Add-GSUserLocation` which will build the correct data type.

Feel free to reach out if you have any questions or issues!

**Comment by gfree23** [comment]
Wow, thanks @scrthq !  I really appreciate it!
