### ISSUE TITLE
[Google.Apis.Util.Store.FileDataStore] does not contain a method named 'new'

### ISSUE THREAD

**Issue by lefoimpeur** [scrthq/PSGSuite#172]
Hi,

After creating the PSGSuite Configuration File, i've got this error with the command line "Get-GSGmailProfile -Verbose" :

`Get-GSGmailProfile : Method invocation failed because [Google.Apis.Util.Store.FileDataStore] does not contain a method named 'new'.`

Help please

**Comment by lefoimpeur** [comment]
I'm using PSGSuite version 2.26.0

**Comment by scrthq** [comment]
Hi @lefoimpeur - Are you running `Import-Module PSGSuite` after installing or are you immediately trying commands?

Also, what version of PowerShell are you using?

**Comment by scrthq** [comment]
@lefoimpeur - my assumption is that you're on PowerShell v4 and you're using the ClientSecretsPath, not the P12KeyPath, based on the error. Should have a fix for this shortly if that's accurate!

**Comment by scrthq** [comment]
Hey @lefoimpeur - Please update to v2.26.1 and let me know if you are still having any issues! Reopening this until I have your confirmation

**Comment by lefoimpeur** [comment]
Hi, thank you for your help.
Indeed I'm using PS v4. I will test next week because I'm in holidays.

**Comment by scrthq** [comment]
Sounds good!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lefoimpeur** [comment]
It's ok, good job :)
Thank you for the reactivity!

**Comment by scrthq** [comment]
Awesome! Thanks for confirming, @lefoimpeur !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
