### ISSUE TITLE
Accessing IM Field?

### ISSUE THREAD

**Issue by Mschram72** [scrthq/PSGSuite#179]
Is it possible to access the IM field under (Get-GSUSER -primaryemail useremail@test.com).IMS.IM ?

I can read the value, but cannot find a way to update it, or to create a new user with something in this field.

**Comment by scrthq** [comment]
Hey @Mschram72 - I do believe you're correct in that it's not yet supported, but should be an easy one to add =]. Sanity checking to confirm right now, thanks for popping in on the other issue too!

**Comment by Mschram72** [comment]
Thanks so much :D !

**Comment by scrthq** [comment]
Confirmed it does not exist yet! Should have this added in within the next couple days 💪 

It will be added in as the `IM` parameter on New-GSUser and Update-GSUser and will have a helper function `Add-GSUserIM` to create the correct type. If you're comfortable with using .NET directly from PowerShell, you can bypass the helper function and instantiate the required type like so:

```powershell
[Google.Apis.Admin.Directory.directory_v1.Data.UserIm]@{
    Im             = 'scrthq'
    Primary        = $true
    Type           = 'home'
    Protocol       = 'custom_protocol'
    CustomProtocol = 'twitter'
}
```

**Comment by scrthq** [comment]
(that will still depend on the parameter being added to the `New-GSUser` and `Update-GSUser` functions though)

**Comment by Mschram72** [comment]
Perfect!  This is going to save me a ton of time!  Thanks so much for your help, and for the excellent set of cmdlets!!

**Comment by scrthq** [comment]
Happy to help, I'm glad the module is useful for you! 💟

**Comment by scrthq** [comment]
Hey @Mschram72 - v2.26.2 is out now with IM management support. Please try it out and let me know if you're having any issues! Thanks for your patience!

**Comment by Mschram72** [comment]
Works perfectly!  Thanks so much mate!

**Comment by scrthq** [comment]
You bet @Mschram72 !! <3
