### ISSUE TITLE
unable to suspend Gsuite account

### ISSUE THREAD

**Issue by indianwind** [scrthq/PSGSuite#180]
**Describe the bug**
when i try to disable a Gsuite account using update-GSuser, i got the following error.

**To Reproduce**
1. Update-GSUser  -PrimaryEmail chienv@tas.tw -Suspended $true under PowerShell
2. 
3. 
4. 

**Expected behavior**
suspend his Gsuite account

**Screenshots**

![image](https://user-images.githubusercontent.com/48904172/56190681-52ddbf80-605d-11e9-8a6e-efedb70cceb7.png)

**Environment (please complete the following information):**
 - OS:  Win 10.0.10586
 - 
![image](https://user-images.githubusercontent.com/48904172/56190821-b10aa280-605d-11e9-9140-0dbac565ec59.png)

**Comment by Mschram72** [comment]
Syntax is actually:

Update-GSUser -PrimaryEmail chienv@tas.tw -Suspended:$true

**Comment by scrthq** [comment]
@indianwind - You'll need to make sure you're using the user's PrimaryEmail or unique ID. The error seen will happen if you do not have a user in your domain with that PrimaryEmail. 

Also worth noting that `Suspended` is a Switch parameter, so you can simply pass `-Suspended` to set it as true. If you want to be verbose in your script, use `-Suspended:$true` to visibly flag it as `True`. If you want to unsuspend someone, use `-Suspended:$false`.

Try this out:

```powershell
Get-GSUser chienv@tas.tw | Update-GSUser -Suspended
```

**Comment by indianwind** [comment]
thx scrthq, it's working great :D
