### ISSUE TITLE
Add-GSDrivePermission does not support fileOrganizer role for Team Drives

### ISSUE THREAD

**Issue by aitcriver** [scrthq/PSGSuite#182]
**Describe the bug**
Team Drives support a "Content Manager" role, which is called "fileOrganizer" in the API. However, PSGsuite currently does not support this role.

**To Reproduce**
1. Add-GSDrivePermission -User testuser@domain.com -FileId TeamDriveID -role fileOrganizer -Type User -EmailAddress testuser2@domain.com

**Expected behavior**
The role should be added to the Team Drive.

**Environment (please complete the following information):**
 - OS:  Ubuntu
 - PowerShell Version:  Core 6.2.0
 - PSGSuite Version:  2.26.2

**Additional context**
In Add-GSDrivePermission.ps1, updating line 88 to include fileOrganizer in the ValidateSet, and updating line 168 to:
`$body.$key = ($PSBoundParameters[$key]).ToLower().Replace("fileorganizer","fileOrganizer")`
should do the trick (it works in my local environment). It seems the underlying API unfortunately requires the uppercase O.

**Comment by scrthq** [comment]
Thank you so much for the detailed analysis and quick fix! Google is definitely sensitive when it comes to casing, camelCase all the things. I'll add it in asap!

**Comment by scrthq** [comment]
hey @aitcriver - you should be good to go now on the latest version. Try it out and let me know!
