### ISSUE TITLE
Update/Set group type ie distribution/discussion/collaborative inbox

### ISSUE THREAD

**Issue by n-searle** [scrthq/PSGSuite#184]
Hiya,

Is it possible to add the functionality to set group type with Set-GSGroupSettings / Update-GSGroupSettings.

I would like to be able to create groups and set them to one of the following:
![image](https://user-images.githubusercontent.com/44114177/56948618-9d187380-6b28-11e9-94c0-051c86e19ee4.png)

Cheers

P.S the cached sessions are working excellently :D

**Comment by scrthq** [comment]
Hey @n-searle - I don't think the API supports those types directly out of the box, but I should be able to add something like a `Template` parameter that has those as options and wraps the actual settings that correspond to each. Checking it out!

**Comment by scrthq** [comment]
and awesome to hear about the cached sessions! that's fantastic :D

**Comment by scrthq** [comment]
So it looks like the only Group Type that can be adjusted with the latest version of the API is Enabling/Disabling the Collaborative Inbox feature:

![image](https://user-images.githubusercontent.com/12724445/57091669-8e63c500-6cbe-11e9-9870-cc2a4e65b69e.png)

I'l get that added in ASAP and see if there's a way to pass the canned settings for the other group types or if those truly aren't doable

**Comment by n-searle** [comment]
Hey,

That sounds great, the collaborative inbox feature was the one I was mainly looking for but if there is a way to template the others that sounds even better.

Thanks for looking into it :)

**Comment by scrthq** [comment]
hey @n-searle - this will likely take me a little bit to implement, primarily since the field is read-only either until Monday when the update for that API goes live or possibly indefinitely read-only, but I'll need to wait until at least next week to test. I'll try and work on what I can in the meantime :D

**Comment by scrthq** [comment]
Hey @n-searle - This should be doable now in 2.29.0! `EnableCollaborativeInbox` is a new Switch parameter on `Update-GSGroupSettings`. Pass as-is to enable, otherwise flag as false to disable, i.e. `Update-GSGroupSettings -EnableCollaborativeInbox:$false ....`

**Comment by n-searle** [comment]
Heya,

Awesome, thanks for implementing :)
