### ISSUE TITLE
Running commands via admin with non-ASCII character in user name fields

### ISSUE THREAD

**Issue by Lopson** [scrthq/PSGSuite#189]
**Describe the bug**
After going through the first-time setup for a G Suite Admin, no command works seemingly due to my name having non-ASCII characters, namely "ç".

**To Reproduce**
1. Configure PSGSuite as per indicated by the first-time setup without indicating the "CustomerId" in Set-PSGSuiteConfig;
2. Run any cmdlet;
3. Get error 'Exception calling "Execute" with "0" argument(s): "The format of value 'Gonçalo Lourenço google-api-dotnet-client/1.40.0.0 (gzip)' is invalid."'.

**Expected behavior**
Commands running correctly without the above-mentioned error.

**Logs**
```
get-gsuser : Exception calling "Execute" with "0" argument(s): "The format of value 'Gonçalo Lourenço google-api-dotnet-client/1.40.0.0 (gzip)' is invalid."
At line:1 char:1
+ get-gsuser
+ ~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GSUser
```
**Environment (please complete the following information):**
 - OS: Windows 10 1809
 - PowerShell Version:  Core 6.2.0
 - PSGSuite Version: 2.27.0 (PSGallery)

**Comment by scrthq** [comment]
Hey @Lopson - Thank you for raising this!! The error appears to be related to the underlying Google .NET SDK that PSGSuite uses. Just to check, you entered your Email for the `AdminEmail` parameter when you created your config, not `Gonçalo Lourenço`, right? You can check what's there using `Show-PSGSuiteConfig`

**Comment by Lopson** [comment]
Hey @scrthq! Yup, that I did, lemme copy-paste my config:
```
ConfigName             : GSuite
P12KeyPath             : C:\Users\Gonçalo Lourenço\Documents\Keys\psgsuite-project-61059cf017d9.p12
P12Key                 : {Redacted…}
ClientSecretsPath      :
ClientSecrets          :
AppEmail               : psgsuite-sa@redacted.iam.gserviceaccount.com
AdminEmail             : goncalo.lourenco@redacted.com
CustomerID             : Redacted
Domain                 : redacted.com
Preference             : CustomerID
ServiceAccountClientID : Redacted
Chat                   : {Webhooks, Spaces}
ConfigPath             : C:\Users\Gonçalo Lourenço\AppData\Local\powershell\SCRT HQ\psgsuite\Configuration.psd1
```

**Comment by scrthq** [comment]
Thanks for confirming @Lopson ! When you use Google's API Explorer to run the same API call through their REST API, does it throw an error there as well or does it go through fine? You'll want to test at right-side of the following link, entering your AdminEmail for the UserKey parameter:

https://developers.google.com/admin-sdk/directory/v1/reference/users/get

**Comment by Lopson** [comment]
Through the API it works just fine. I tried setting things up on a different computer and it worked flawlessly at first try:

1. I installed PSGSuite via PSGallery as Admin;
2. I generated a new key for the same service account;
3. Cmdlets work as expected.

I'd say the major difference between setups is the Powershell version: 5.x in the one that works, 6.x in the one that doesn't work. I'll try creating a new key once I'm back on the computer in which the module doesn't work and will let you know the results!

**Comment by scrthq** [comment]
Interesting!! Are you using Core on Windows also or a different OS?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Lopson** [comment]
Yeah, the PC on which it didn't work was the one in the original report, an up-to-date Windows 10 with PS Core 6.2.0, while the one that worked first try is also an updated Windows 10 machine using PS 5.1. I'll let you know how my experimentation goes tomorrow!

**Comment by Lopson** [comment]
Tried using PowerShell 5.1 on the computer in which the module isn't working and it made no difference. 

I actually have a theory: I don't think this is related to my G Suite account at all, but rather it has to do with my account in this computer. My account's name is "Gonçalo Lourenço" as seen in my second post, and by account name I'm not talking about display name, it's the actual name of the account in the Local Users MMC.

What do you think? Is it possible that my local account name is throwing things off?

**Comment by Lopson** [comment]
I gave my theory a try and it worked! I created a new user in the same computer with the username "goncalo.lourenco", replicated the configuration I have for PSGSuite in my other account, and the commands started working correctly.

**Comment by scrthq** [comment]
Super unexpected! I'll see if I can replicate with a non-standard user and work on debugging if so! Thanks again for raising this issue and going through the overall fix @Lopson !

**Comment by Lopson** [comment]
Thank YOU for coming up with this fantastic module! If you need any help with further debugging, let me know!

**Comment by scrthq** [comment]
❤️ ❤️ ❤️

**Comment by scrthq** [comment]
hey @Lopson - I was able to find a reference to `$env:UserName` in `New-GoogleService`, which created the initial client. Can you update when possible to v2.31.1 and let me know if you're still getting this bug? I'm hoping that was the underlying issue.

**Comment by scrthq** [comment]
hey @Lopson - It's been a bit since my last post so I'm going to close this out. Please let me know if you feel this is still an issue after the changes were made to `New-GoogleService` and I can get this reopened to continue tracking.
