### ISSUE TITLE
Get-GSDriveFile -Fields parameter is never honored

### ISSUE THREAD

**Issue by WJurecki** [scrthq/PSGSuite#190]
**Describe the bug**
When `Get-GSDriveFile` is executed with the `-Fields` parameter is not honored and all fields are returned.

This is caused because `-Fields` is only evaluated if `-Projection` is not specified, however  `-Projection` has a default defined as 'Full' and there is no way to prevent this.  Therefore, `-Fields` are never evaluated and utilized.

**To Reproduce**
1. `Get-GSDriveFile -FileId '1234'`
2. `Get-GSDriveFile -FileId '1234' -Fields 'id'`

Both have same result with all fields returned and populated.

**Expected behavior**
when `Get-GSDriveFile -FileId '1234' -Fields 'id'` is used the returned object should only have the `id` property filled.

**Comments**
Simply removing the default on `-Projection` fixes this immediate problem, but, significantly changes default behavior.  Reversing the logic so as to check `-Fields` first could allow a less impactful 'fix'.  I'm not certain what to suggest as the best solution.

**Environment (please complete the following information):**
 - OS:  Windows 10 1803.17134.706
 - PowerShell Version:  Windows PowerShell 5.1.17134.590 
 - PSGSuite Version:  2.27.0

**Comment by scrthq** [comment]
@WJurecki - Thanks for opening this up! I'm on it, I appreciate the detail!

**Comment by scrthq** [comment]
@WJurecki - `Fields` is working correctly now:

![image](https://user-images.githubusercontent.com/12724445/58686990-f224f080-8345-11e9-8bd1-de36098b1b91.png)

with default behavior untouched and still picking up the default value for `Projection`:

![image](https://user-images.githubusercontent.com/12724445/58687020-0668ed80-8346-11e9-820d-0a1016febb46.png)


![yes](https://media1.giphy.com/media/nXxOjZrbnbRxS/giphy.gif)

**Comment by scrthq** [comment]
Hey @WJurecki - This has been deployed in v2.28.0! Let me know if all is well or if you are seeing any issues!

**Comment by WJurecki** [comment]
Hey @scrthq - This works great.  Thanks!

**Comment by scrthq** [comment]
You bet @WJurecki !!
