### ISSUE TITLE
Functions for "Restore Data"

### ISSUE THREAD

**Issue by IronKane2** [scrthq/PSGSuite#192]
I absolutely love PSGSuite!  Now give me more :)
I just now finished restoring data manually for 17 students.  First place I went to was PSGSuite thinking I could knock this out in just a couple of minutes.  I'm hoping you can add to the toolbox a Restore Data set of functions for Drive.

Thanks Nate!

**Comment by scrthq** [comment]
Hey @IronKane2 - Do you happen to have a link to the API page covering what you're trying to do? I know that data restoration can mean various things (Vault restoration, old version retrieval, etc), just want to make sure I understand what you're after and if it's something that is open via public API

**Comment by scrthq** [comment]
For example, I'm not seeing anything in the API docs for Admin SDK or Drive SDK that highlight data restoration in particular. The closest thing would be the Data Transfer API, but that's not exactly a restore. The only way to restore data from the Admin console is only doable from the console itself (as far as I'm aware), not via API: https://support.google.com/a/answer/6052340?hl=en

**Comment by IronKane2** [comment]
Well damn.  Thanks for the update.  Hopefully Google will make an API for this sometime soon.
What about this --> https://developers.google.com/drive/api/v2/reference/files/untrash
Not applicable?

**Comment by scrthq** [comment]
So that exact method isn't doable (it's using the legacy v2 of the Drive API), but the equivalent method could be something to add to `Update-GSDriveFile` as a switch parameter: https://developers.google.com/drive/api/v3/reference/files/update

Example of the final product:

```powershell
Update-GSDriveFile -FileId $fileId -Trashed:$false
```

Thoughts?

**Comment by IronKane2** [comment]
Please don't waste any more time on this.  It sounds like we'll have to wait for future API's from Google.  
I'm using PSGSuite every day.  Thank you so very much.

**Comment by scrthq** [comment]
I'll keep it backlogged for now, shouldn't be terribly difficult to implement =]. There's value there, for sure

**Comment by scrthq** [comment]
Hey @IronKane2  - This has been deployed in v2.28.0! Let me know if all is well or if you are seeing any issues!
