### ISSUE TITLE
[Enhancement] Update-GSChromeOSDevice

### ISSUE THREAD

**Issue by Foggy2** [scrthq/PSGSuite#194]
It would be great if we could update the following ChromeOS device fields in Google Directory:

- Asset ID (annotatedAssetID)
- User (annotatedUser)
- Notes (notes)
- Location (AnnotatedLocation)

I think this would fit in with `Update-GSChromeOSDevice' perfectly.

Thanks!

**Comment by scrthq** [comment]
Hey @Foggy2 - [Looks doable](https://developers.google.com/admin-sdk/directory/v1/reference/chromeosdevices/update)! Checking it out, thanks!

**Comment by scrthq** [comment]
Hey @Foggy2 - This has been deployed in v2.28.0! Let me know if all is well or if you are seeing any issues!

**Comment by Foggy2** [comment]
Hi @scrthq 
I have been trying out this new feature but I have not been having any luck.
![Capture](https://user-images.githubusercontent.com/23325075/58926691-30c60b00-878b-11e9-9438-168e3732778b.PNG)
Each time I run the command, it appears to succeed but the properties on the device are not changed.

**Comment by scrthq** [comment]
if you do a Get-GSChromeOSDevice for that device after, does it still show as not updated? I've noticed some of Google's APIs will do that with update requests, it can be a bit offputting. Sanity checking the source though in case there's something off there!

**Comment by Foggy2** [comment]
No, still blank unfortunately.
![image](https://user-images.githubusercontent.com/23325075/58927911-961bfb00-878f-11e9-9d65-99cdf3f8b0a9.png)

**Comment by scrthq** [comment]
🤔 checking it out! Thanks for letting me know @Foggy2 !

**Comment by Foggy2** [comment]
I think I see the issue.

Line 155 of `Update-GSChromeOSDevice` is
`$request = $service.Chromeosdevices.Patch($actionBody,$customerId,$dev)`
But I think it should be
`$request = $service.Chromeosdevices.Patch($Body,$customerId,$dev)`

**Comment by scrthq** [comment]
You are 100% correct! Thanks for hunting that down, pushing a build now!

**Comment by scrthq** [comment]
@Foggy2 - alrighty, can you update to 2.28.2 and let me know? I'd test but I don't have any Chrome OS devices in either domain tbh 😨

**Comment by Foggy2** [comment]
@scrthq Looks to be working as expected now. Thanks for your work on this!

**Comment by scrthq** [comment]
@Foggy2 - Woohoo! Thanks for your help as well!
