### ISSUE TITLE
New-GSDriveFile -Fields option never honored (just like #190)

### ISSUE THREAD

**Issue by WJurecki** [scrthq/PSGSuite#201]
`New-GSDriveFile -Fields` option never honored (just like #190  )

This, I believe, is the same logic bug you fixed in `Get-GSDriveFile` in bug #190 

This is much less of an issue as `New-GSDriveFile` creates only one file at a time and therefore only returns the results of one file which fits entirely in one round-trip.  but it's a bug nonetheless.

**Comment by scrthq** [comment]
Very valid finding! I'm going to take this and run with checking any functions out that may have the Fields parameter. If it is expected to work, then by all means it should 😃 

Thanks @WJurecki !!

**Comment by scrthq** [comment]
Should be all wrapped up now! Thanks for opening this up @WJurecki !
