### ISSUE TITLE
Add-GSTeamDriveMember

### ISSUE THREAD

**Issue by n-searle** [scrthq/PSGSuite#207]
Hi Nate,

Is there already a way to add users as members to a team drive and set their permissions?

I have tried:
`Update-GSTeamDrive -TeamDriveId 0AMJaWArZXy3jUk9PVA -User my-test-user -CanComment`

but get:
Update-GSTeamDrive : Exception calling "Execute" with "0" argument(s): "Google.Apis.Requests.RequestError
The operation was successful, but there was an error preparing the response. [500]
Errors [
        Message[The operation was successful, but there was an error preparing the response.] Location[ - ]
Reason[responsePreparationFailure] Domain[global]
]
"
At line:1 char:1
+ Update-GSTeamDrive -TeamDriveId 0AMJaWArZXy3jUk9PVA -User my-test-use ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Update-GSTeamDrive

Cheers,
Neil

**Comment by n-searle** [comment]
As an additional I would like to be able to add users and groups as members to team drives.

**Comment by scrthq** [comment]
hey @n-searle - Totally doable! You can see a sample below, but the command you're looking for is `Add-GSDrivePermission 😃 There's a `Type` parameter on that where you specify if the permission is for a User, a Group, the Domain, or Anyone:

```powershell
Add-GSDrivePermission -User $OwnerOfDriveFile -FileId $TeamDriveId -Role Commenter -Type User -EmailAddress my-test-user@domain.com
```

**Comment by n-searle** [comment]
Awesome, will give it a shot cheers.

**Comment by scrthq** [comment]
Cool! Let me know if you run into any issues, otherwise close this out if you're comfortable!
