### ISSUE TITLE
SuspensionReason of Get-GSUser does not list 'Automatically Suspended'

### ISSUE THREAD

**Issue by BarnumD** [scrthq/PSGSuite#208]
**Describe the bug**
Perhaps this is an issue on Google's side and not PSGSuite, but I have a user that was 'Automatically Suspended' by google (see image below) due to suspicious account activity.  However, when I use Get-PSUser against this account there is no information under `SuspensionReason`.  Perhaps Google is just not putting any information into that field when they lock an account or perhaps PSGSuite could do more to get that information.  I don't know.  Let me know which is the case.

**Expected behavior**
Expect `SuspensionReason` to include 'Automatically Suspended by Google' information.

**Screenshots**
![image](https://user-images.githubusercontent.com/2438253/60982823-dc242b80-a306-11e9-8c67-5c83e40ee734.png)

**Comment by scrthq** [comment]
Hey @BarnumD - Are they showing anything at all under `SuspensionReason`? And are they showing `Suspended : True`? I've honestly only ever seen `ADMIN` as the SuspensionReason, but I also haven't checked under the exact circumstances you're seeing as it doesn't happen all that often. At any rate, PSGSuite isn't manipulating the data returned the Directory API, so what you're seeing in PSGSuite is what Google is returning.

Here's a sample showing a working user vs suspended user:

![image](https://user-images.githubusercontent.com/12724445/60983393-77190780-a2ff-11e9-892c-8981ca112220.png)

**Comment by BarnumD** [comment]
No, SuspensionReason is completely blank.  Suspended is `True`.  So I take it that there's nothing you can do about it.  What about the ability to set that `SuspensionReason` field from the module?  Should I open a feature request for that?

**Comment by scrthq** [comment]
That field is actually ReadOnly/not writable on the API itself, so we're a little stuck with what Google provides here, unfortunately:

[Doc Link](https://developers.google.com/admin-sdk/directory/v1/reference/users)

![image](https://user-images.githubusercontent.com/12724445/60984258-0246cd00-a301-11e9-9959-b54b87723087.png)

**Comment by BarnumD** [comment]
Thanks for the information.  Very helpful.  I just wish Google would have provided the reason.

**Comment by scrthq** [comment]
100% agreed! That field could be so much more useful 😞
