### ISSUE TITLE
Data Transfer calendar release ressources

### ISSUE THREAD

**Issue by ABricka** [scrthq/PSGSuite#213]
Hi @scrthq , i can't find any solution to your Start-GSDataTransfer command for apply the release_ressource parameter.
I imagine is possible cause "GAM" do it but I don't want to use gam only for this so if you got any hidden feature or whatever to do it I'll be very happy :)

For "help" there is the gam command in first and my command in 2nd i want to implement the release ressource : 
>```powershell
> gam create datatransfer oldguy@acme.com calendar newguy@acme.com release_resources true
>
> Start-GSDataTransfer -OldOwnerUserId $username -NewOwnerUserId $Ownershipuname -ApplicationID 435XXXXXXXXX -PrivacyLevel SHARED
>```

Alex

**Comment by scrthq** [comment]
Hey @ABricka - It looks like that Start-GSDataTransfer needs to be updated to support it! `Privacy_Level` is Drive and Docs specific, but I'm seeing the `RELEASE_RESOURCES` TransferParam on the Calendar DataTransferApplication specifically:

![image](https://user-images.githubusercontent.com/12724445/61804816-34c0f180-adfa-11e9-9fe8-eb7ff8de923c.png)

Considering this a feature request, I'll let you know once available!

**Comment by ABricka** [comment]
Super :) That's a great new !
Waiting about you to use it :)
Thanks a lot for this fast reaction 👍

**Comment by scrthq** [comment]
Hey @ABricka - added support for this in 2.31.0! Usage (note that `ReleaseResources` is a `[Switch]` parameter, so no need to pass `$true`):

```powershell
$calendarApp = Get-GSDataTransferApplication | Where-Object {$_.Name -eq 'Calendar'}
Start-GSDataTransfer -OldOwnerUserId $username -NewOwnerUserId $Ownershipuname -ApplicationID $calendarApp.Id -ReleaseResources
```

**Comment by ABricka** [comment]
Super, thanks a lot 👍

**Comment by scrthq** [comment]
You bet!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
