### ISSUE TITLE
Add a file to a shared drive

### ISSUE THREAD

**Issue by jtwaddlegus** [scrthq/PSGSuite#214]
Unless I am missing it, I don't see a way to move a file from My Drive into a shared drive.  Is that possible?

**Comment by WJurecki** [comment]
It took me a while to find it too!
 
`Update-GSDriveFile -FileId 'fileid' -AddParents 'SharedDriveID' -RemoveParents 'ExistingParents' 
`

**Comment by jtwaddlegus** [comment]
Thank you!

**Comment by scrthq** [comment]
Thanks for the assist, @WJurecki!!!

Glad you're sorted, @jtwaddlegus!!! 

❤️
