### ISSUE TITLE
Feature Request: Get list of domains

### ISSUE THREAD

**Issue by BarnumD** [scrthq/PSGSuite#215]
Which command can be used to print a list of all domains on the account similar to how gam does it with `/gam print domains`?

**Comment by scrthq** [comment]
hey @BarnumD - Domain info is still yet to be added, but I'll consider this a feature request!

This should be the API docs around what you're after (correct me if I'm wrong): https://developers.google.com/admin-sdk/directory/v1/reference/domains/list

Should have this turned around for you soon, I'll keep you updated!

**Comment by BarnumD** [comment]
Looks like it.  Thanks.

**Comment by scrthq** [comment]
@BarnumD added in 2.31.0!
