### ISSUE TITLE
Upgrade to PSGSuite 2.1.5

### ISSUE THREAD

**Issue by cooper** [scrthq/PSGSuite#22]
I am trying to upgrade to PSGSuite 2.1.5. I extracted the .zip from the releases page, but now when I try to use any of the cmdlets, it says the required module 'Configuration' is not loaded. So, I checked the Initial Setup guide to see how to re-configure. Guide says to use Set-PSGSuiteConfig, but when I try to do so, it says: the command was found in the PSGSuite module, but the module could not be loaded (because it can't load the Configuration). I am guessing I skipped a step somewhere...?
![psgsuite](https://user-images.githubusercontent.com/323847/36996641-49f2faa2-2085-11e8-9b32-9b2d0c1f67b4.PNG)

**Comment by scrthq** [comment]
Thanks for bringing this up! I should update the docs to note that, but you would need to install the Configuration module from PoshCode prior: 

[GitHub Link](https://github.com/poshcode/configuration)
[PowerShell Gallery Link](https://www.powershellgallery.com/packages/Configuration/1.2.0)

If you're installing through PowerShellGet + Install-Module, it would resolve those dependencies directly from the PowerShell Gallery and get you sorted on installation, but that does not happen if you do a manual install from releases like you're doing here.


Let me know if you need any further info!! I'll leave this open until you're fully squared away!

**Comment by cooper** [comment]
I was able to install it withPowerShellGet. Thank you!

**Comment by scrthq** [comment]
Awesome!
