### ISSUE TITLE
Forwarding has been changed to a "Recipient Mapping"

### ISSUE THREAD

**Issue by ryanfog** [scrthq/PSGSuite#220]
**Describe the bug**
The method of setting a forward is no longer working. It appears that Google may have updated its API. The new method appears to be via "recipient mapping"

Scenario: You are migrating from Google to Exchange and you need to forward new messages over to Exchange.

**Comment by scrthq** [comment]
Hey @ryanfog - Are you talking about adding a ForwardingAddress via Gmail API? Documentation appears the same in regards to that: https://developers.google.com/gmail/api/v1/reference/users/settings/forwardingAddresses/create

What PSGSuite function is impacted by this change? If you're referring to [this](https://support.google.com/a/answer/4524505?hl=en), that wouldn't impact PSGSuite (or any API usage) that I'm aware of as there isn't a way to manage that setting via API call (that comes to mind anyway)

**Comment by Hummuna** [comment]
@scrthq  I get a 500 error from the API response. When attempting to do this manually I noticed this.
![GSuiteForwarding](https://user-images.githubusercontent.com/40130792/62309782-2441f400-b456-11e9-8235-7014b6a071a0.png)

Considering forwarding is no longer able to be done at the end user level but rather requires it to be done at the application configuration level I believe that is why the API is responding with a 500 error. 

Recipient Mapping over taking the Forwarding Address

**Comment by scrthq** [comment]
What API are you trying to use? There's no API that I'm aware of that can manage the Email Routing within Gmail Advanced Settings. Still a bit confused as to what's breaking in PSGSuite tbh @ryanfog

**Comment by scrthq** [comment]
+ @Hummuna  ^^

**Comment by Hummuna** [comment]
@scrthq  Not sure why but I am now getting a healthy response I suppose not an error. I wish I could have grabbed a screenshot of the error but working off client laptop and blocks githug.

Response I am getting now using Add-GSGmailFowardingAddress is 

USER, ForwardingEmail, VerificationStatus


Status is returned pending

**Comment by scrthq** [comment]
Got it! So that would be different than the screenshot you posted above. The one above is email routing, which isn't configurable via API call, but you're working on adding a forwarding address via Gmail API. Similar, but different. 

The response status is pending as the forwarding address will receive an email to confirm they accept the user adding their address as a forwarding address. This is typical.

**Comment by scrthq** [comment]
hey @ryanfog + @Hummuna - closing this since it's regarding changes with Email Routing, not Forwarding Addresses in Gmail API. Let me know if there are any questions regarding this!
