### ISSUE TITLE
Star Google Group for a user

### ISSUE THREAD

**Issue by jtwaddle** [scrthq/PSGSuite#223]
We are trying to find a way for users with a large number of Google Groups they are part of to have it list just the ones they are owners of.  We had the idea of staring the groups so that they show up in the users favorite list.  Do you know if it is possible to star a group for a user using the API?

**Comment by scrthq** [comment]
hey @jtwaddle - I don't believe it is, as Groups/Group Settings APIs aren't scoped to the authenticated user like Gmail/Drive/Calendar are, so typically actions performed there would be what you can do from the Admin Console or the Groups Service page as the admin directly. Checking though!

**Comment by scrthq** [comment]
Yeah, not seeing any functionality around that in the API, unfortunately. This would be done on the Groups Service directly, where API access is already limited to just Group Settings only

**Comment by jtwaddle** [comment]
Thank you for checking!
