### ISSUE TITLE
Ability to view and update recoveryEmail and recoveryPhone fields using Get-GSUser and Update-GSUser

### ISSUE THREAD

**Issue by citmpz** [scrthq/PSGSuite#225]
**Is your feature request related to a problem? Please describe.**

The ability to work with recoveryEmail and recoveryPhone fields.

**Describe the solution you'd like**

Google has now standardized recoveryEmail and recoveryPhone as fields available for edit. See https://gsuiteupdates.googleblog.com/2019/08/admins-can-edit-user-recovery-security-details.html

**Describe alternatives you've considered**

Manually working with Goolge's API is still possible, but heavy to implement when client libraries/PSGSuite is available and feature-rich.

**Additional context**

Just wanted to say thanks for maintaining this! It's a great code base. :)

**Comment by scrthq** [comment]
Hey @citmpz - Thanks for opening this up! I'll get this in ASAP, shouldn't be too difficult. Worth noting that the .NET SDK doesn't yet include the [additional properties on the User object](https://developers.google.com/resources/api-libraries/documentation/admin/directory_v1/csharp/latest/classGoogle_1_1Apis_1_1Admin_1_1Directory_1_1directory__v1_1_1Data_1_1User.html), but it may actually be there just pending a doc update. The REST API docs do have the properties listed though, so if it's not actually in the .NET SDK yet, I expect it to be soon.

**Comment by scrthq** [comment]
Doesn't appear that the .NET SDK's User object supports this _yet_, but I'll keep an eye on it! Just tried building with the latest SDK versions and am not seeing it 😢 

![image](https://user-images.githubusercontent.com/12724445/63380482-44314d00-c35c-11e9-897e-2af5eb887fbc.png)

**Comment by scrthq** [comment]
Documentation still doesn't show support, but I can confirm that the updated SDK does actually have the Recovery fields now! Working on getting this added as soon as possible @citmpz ! I'll keep you updated!

![image](https://user-images.githubusercontent.com/12724445/63990121-6d628380-caa8-11e9-899a-cd914f790f3b.png)

**Comment by scrthq** [comment]
Available now in v2.31.1! @citmpz

**Comment by citmpz** [comment]
Still can't see these fields. I've updated to PSGSuite version 2.32.1. Do I need to do anything further to see these new fields?

**Comment by scrthq** [comment]
So, oddly enough, that specific SDK seems to have fallen back to the version in repo instead of pulling from NuGet like the rest did. Getting it fixed ASAP and adding more guards to ensure this doesn't happen again! Thanks for raising awareness!

**Comment by scrthq** [comment]
Got is sorted and deployed in PSGSuite 2.32.2! Please let me know if this happens again, I appreciate the heads up!

**Comment by citmpz** [comment]
Tested and working fine. Thank you!

On Mon, Sep 16, 2019 at 12:04 AM Nate Ferrell <notifications@github.com>
wrote:

> Closed #225
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scrthq_PSGSuite_issues_225&d=DwMCaQ&c=w_KKIrnflabZu7RVO9QOig&r=LRkNW-4X7IlTsf94gKur_5oSou9IZYvd0_Gj2k3QvH0&m=7r4qS5IMCciLiS5_Gg7sLdRQ7gsRJZiDXoK_DlAo6qg&s=yIjNcdQ2RH5TeUlZ7vDcQkiO_qRkOQ-SgAdRsq-aMDI&e=>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scrthq_PSGSuite_issues_225-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAJMGFWPCSJISM4V3VGO3QITQJ4AV3A5CNFSM4IMS5OT2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOTUIO3IQ-23event-2D2635132322&d=DwMCaQ&c=w_KKIrnflabZu7RVO9QOig&r=LRkNW-4X7IlTsf94gKur_5oSou9IZYvd0_Gj2k3QvH0&m=7r4qS5IMCciLiS5_Gg7sLdRQ7gsRJZiDXoK_DlAo6qg&s=bzu75ppz4asQ_3gaKXItp0essneUsNYKr8P1qsPOtvI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJMGFWMXCNU7D2PMPXTHRC3QJ4AV3ANCNFSM4IMS5OTQ&d=DwMCaQ&c=w_KKIrnflabZu7RVO9QOig&r=LRkNW-4X7IlTsf94gKur_5oSou9IZYvd0_Gj2k3QvH0&m=7r4qS5IMCciLiS5_Gg7sLdRQ7gsRJZiDXoK_DlAo6qg&s=IbsZOhP5XQCc6AaKGsTgh2JcsL5goj51k99loIfG9Fc&e=>
> .
>


-- 

*Marcel Penton*

IT Security Analyst, Cloud
Enterprise Infrastructure & Security




*Empire Life*

259 King Street East,
<https://maps.google.com/?q=259+King+Street+East,%C2%A0+Kingston,%C2%A0Ontario,%C2%A0%C2%A0K7L+3A8&entry=gmail&source=g>Kingston,
Ontario,  K7L
3A8
<https://maps.google.com/?q=259+King+Street+East,%C2%A0+Kingston,%C2%A0Ontario,%C2%A0%C2%A0K7L+3A8&entry=gmail&source=g>

*t *613 548-1890 x 3686 | *toll free *1 877 548-1881 x 3686 | *c *613
317-8771 | *f *613 548-8524

*Insurance & Investments – Simple. Fast. Easy.*
*www.empire.ca <http://www.empire.ca/>*

<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.facebook.com_EmpireLife_&d=DwMFaQ&c=w_KKIrnflabZu7RVO9QOig&r=LRkNW-4X7IlTsf94gKur_5oSou9IZYvd0_Gj2k3QvH0&m=85mBvuHnPD49MC6jYNRg47MVsVhO0KrFfiPsMMMw898&s=XmsPVRD3yiBZeKF6NaahdWkl3S5x3h1uHnCHLPhdEYg&e=>

<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.linkedin.com_company_empire-2Dlife_&d=DwMFaQ&c=w_KKIrnflabZu7RVO9QOig&r=LRkNW-4X7IlTsf94gKur_5oSou9IZYvd0_Gj2k3QvH0&m=85mBvuHnPD49MC6jYNRg47MVsVhO0KrFfiPsMMMw898&s=_BuygR4labAOXofJAFADiMZlRQd4_19GwJ9nuZ0Pv2Q&e=>

<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_EmpireLife&d=DwMFaQ&c=w_KKIrnflabZu7RVO9QOig&r=LRkNW-4X7IlTsf94gKur_5oSou9IZYvd0_Gj2k3QvH0&m=85mBvuHnPD49MC6jYNRg47MVsVhO0KrFfiPsMMMw898&s=wxN_iBB6EJ3HQ4j7JYBQ7F5n9SIFpbMs6WvKhwwkVEY&e=>

<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.instagram.com_empirelife_&d=DwMFaQ&c=w_KKIrnflabZu7RVO9QOig&r=LRkNW-4X7IlTsf94gKur_5oSou9IZYvd0_Gj2k3QvH0&m=85mBvuHnPD49MC6jYNRg47MVsVhO0KrFfiPsMMMw898&s=MlHe6YmlVoVETaDhfp52gf6GswsFGStSC3_fpSxih4o&e=>



*Be environmentally friendly – please print only if necessary*

-- 
The content of this message is subject to our e-mail confidentiality 
policy. <https://static.empire.ca/confidentiality/conf.html> 
Le contenu de 
ce message est assujetti à notre politique en matière de confidentialité 
des courriels. <https://static.empire.ca/confidentiality/conf.html>

**Comment by scrthq** [comment]
You bet!
