### ISSUE TITLE
Cant specify -Id on New-GSCourse

### ISSUE THREAD

**Issue by Chris4678** [scrthq/PSGSuite#230]
**Describe the bug**
New-GSCourse works fine as far as I can tell as long as you don't specify an id using the -Id tag. If you do it will throw an error. I tried using the exact line from "example 1" on the wiki page for the command. I only changed the owner email to be my admin account. I still get this same error:
New-GSCourse : Exception calling "Execute" with "0" argument(s): "Google.Apis.Requests.RequestError
Request contains an invalid argument. [400]
Errors [
	Message[Request contains an invalid argument.] Location[ - ] Reason[badRequest] Domain[global]
]
"
**To Reproduce**
1. Setup PSGSuite
2. use the -Id tag on the New-GSCourse command

**Expected behavior**
Error stating you are calling execute with 0 arguments

**Screenshots**

**Environment (please complete the following information):**
 - OS:  [e.g. Windows 2016 server]
 - PowerShell Version: 5.1.14393.3053
 - PSGSuite Version:  Not sure how to tell but I updated it a few weeks ago.

**Additional context**

**Comment by scrthq** [comment]
Hey @Chris4678 - when you're setting the Id, are you setting it in the Alias String format? https://developers.google.com/classroom/reference/rest/v1/courses.aliases#CourseAlias

![image](https://user-images.githubusercontent.com/12724445/64547453-2e2b0280-d2f2-11e9-812c-212b1172ea57.png)

**Comment by scrthq** [comment]
![image](https://user-images.githubusercontent.com/12724445/64547494-47cc4a00-d2f2-11e9-827c-2847f442322e.png)

**Comment by Chris4678** [comment]
OK when I add d: in front of the ID the command runs. However, I cant tell how to then see the alias I just set. When I use get-GSCourseAlias it returns {Google.Apis.Classroom.v1.Data.CourseAlias} How can I see what the actual value of that is?

Also just so you know your wiki page doesn't have anything about needing the d: or p: in the example or description:
https://github.com/scrthq/PSGSuite/wiki/New-GSCourse

**Comment by Chris4678** [comment]
never mind I have figured it out adding a .alias on the output shows what I need.

Thanks for all your help.

**Comment by scrthq** [comment]
Was about to respond but you beat me to it! Glad you're sorted, @Chris4678 !
