### ISSUE TITLE
Turn off calendar notifications

### ISSUE THREAD

**Issue by boldperrotta** [scrthq/PSGSuite#231]
**Is your feature request related to a problem? Please describe.**
When adding a calendar subscription, the function by default enables email notifications for changes to the calendar. $DefaultNotificationType = 'eventChange',

**Describe the solution you'd like**
I would like to have the function to allow for having $DefaultNotificationType as being able to be set to null or none.

**Describe alternatives you've considered**
Currently, only way around it is to open the calendar and turn off the notifications.

**Additional context**

**Comment by scrthq** [comment]
Makes sense! Thanks, @boldperrotta ! I'm on it

**Comment by scrthq** [comment]
Hey @boldperrotta - This is now available in v2.32.0! You'll find a few various helpful bits on `Add-GSCalendarSubscription` as well as the newly added `Update-GSCalendarSubscription`! You'll be most interested on the `RemoveNotifications` switch parameter on `Update-GSCalendarSubscription` if you want to remove notifications from a calendar already in a user's list, while simply not specifying a notification configuration when creating a new subscription will just not add any notifications by default now. I've also done the same for Reminders as well. Check out the [ChangeLog](https://github.com/scrthq/PSGSuite/blob/master/CHANGELOG.md#2320---2019-09-12) for this release for more info, but here's the relevant bits of everything added around this request:

* [Issue #231](https://github.com/scrthq/PSGSuite/issues/231)
  * Added: `Update-GSCalenderSubscription` function to updated existing calendar subscriptions.
  * Removed: Default values for the following parameters on `Add-GSCalendarSubscription` to prevent automatically adding notifications for new CalendarList entries (subscriptions):
    * `DefaultNotificationType`
    * `DefaultNotificationMethod`
    * `DefaultReminderMethod`
    * `DefaultReminderMinutes`
  * Added: `Notifications` and `Reminders` parameters to `Add-GSCalenderSubscription` and `Update-GSCalenderSubscription`
  * Added: `Reminders` parameter to `New-GSCalendarEvent` and `Update-GSCalendarEvent` functions to set custom reminders on calendar events.
  * Added: `Add-GSCalendarEventReminder` and `Add-GSCalendarNotification` helper functions.
  * Updated: `DisableReminder` switch parameter name on `New-GSCalendarEvent` and `Update-GSCalendarEvent` functions to `DisableDefaultReminder` to better align with what that actually effects (default reminder inheritance only, not reminder overrides). The previous parameter name has been set as an alias to maintain backwards compatibility.
  * Added: `RemoveAllReminders` parameter to `Update-GSCalendarEvent` to remove all custom reminders and disable calendar inheritance.
