### ISSUE TITLE
Add event detail visibility to New-GSCalendarEvent Command

### ISSUE THREAD

**Issue by cmason34** [scrthq/PSGSuite#232]
When creating an event on a resource, we would like to be able to set the event visibility to public or private per event.
https://developers.google.com/calendar/v3/reference/events/insert
see visibility property

Thanks!

**Comment by scrthq** [comment]
Thanks, @cmason34 !! On it

**Comment by scrthq** [comment]
hey @cmason34 - This is now available in v2.32.0 on both `New-GSCalendarEvent` and `Update-GSCalendarEvent` :D

**Comment by cmason34** [comment]
Sweet - thanks so much!

**Comment by cmason34** [comment]
We see the visibility parameter on the Update-GSCalendarEvent, but do not
see a parameter for the New-GSCalendarEvent.  We can do updates on our
events, not a huge deal - just making sure we aren't missing something :)

**Comment by scrthq** [comment]
Weird! I'll get it sorted, reopening this to ensure it's tracked! Should definitely be there, IMHO

**Comment by scrthq** [comment]
Available in 2.32.1! Let me know if you spot any issues @cmason34 !

**Comment by cmason34** [comment]
Thanks!  We checked it out yesterday and worked like a charm.

**Comment by scrthq** [comment]
Awesome!!
