### ISSUE TITLE
Get-GSCalendar fails with Method invocation failed because [Google.Apis.Calendar.v3.CalendarsResource] does not contain a method named 'List'

### ISSUE THREAD

**Issue by felixfbecker** [scrthq/PSGSuite#240]
**Describe the bug**
Any call without arguments fails with an error.

**To Reproduce**
Run
```powershell
> Get-GSCalendar
Get-GSCalendar : Method invocation failed because [Google.Apis.Calendar.v3.CalendarsResource] does not contain a method named 'List'.
At line:1 char:1
+ Get-GSCalendar
+ ~~~~~~~~~~~~~~
```

**Expected behavior**
Not error

**Environment (please complete the following information):**
 - OS:  macOS
 - PowerShell Version:  6.2.3
 - PSGSuite Version: 2.33.0

**Comment by scrthq** [comment]
Thanks for opening this up, @felixfbecker !! While I get this fixed, you'll probably want to use `Get-GSCalendarSubscription`. The previous versions actually had that same underlying call replicated between both `Get-GSCalendar` and `Get-GSCalendarSubscription`, so I've been working on cleaning up `Get-GSCalendar` to point at the correct endpoint (`Calendar` vs `CalendarList`). Calendars are a bit of a maze in Google's API

**Comment by scrthq** [comment]
hey @felixfbecker - Fix pushed! You should no longer see those errors. Update to the latest version and let me know =]
