### ISSUE TITLE
Update-GSGmailAutoForwardingSettings returns 403

### ISSUE THREAD

**Issue by scrthq** [scrthq/PSGSuite#25]
Scope is incorrectly set in function, should be using scope 
`https://www.googleapis.com/auth/gmail.settings.sharing`, not `https://www.googleapis.com/auth/gmail.settings.basic`.

Working on fix

**Comment by scrthq** [comment]
![image](https://user-images.githubusercontent.com/12724445/38052564-861e6f08-3286-11e8-80ef-43bed9f3179c.png)

Fix confirmed ^^, checking the rest of the Update-GSGmail* functions to be safe, then pushing out the fix

**Comment by scrthq** [comment]
Confirmed updateAutoForwarding is the only `Users.settings` that uses the `settings.sharing` scope.

pull request submitted with fix and version bump, pending CI tests passing to deploy v2.2.1 to PowerShell Gallery with fix

**Comment by scrthq** [comment]
Fix pushed: https://www.powershellgallery.com/packages/PSGSuite/2.2.1

**Comment by ryanfog** [comment]
Quick question do i have an update or publishing problem that I am not receiving 2.2.1 when i do the following

![capture](https://user-images.githubusercontent.com/25650327/38432483-3455ffca-398d-11e8-8e2a-5a3231a8d547.JPG)

**Comment by scrthq** [comment]
Get-Module will return the currently imported module and modules don't
import on installation by default, so you're likely only showing the
currently imported version.

Try this:

Import-Module PSGSuite -Force
Get-Module PSGSuite
