### ISSUE TITLE
G Suite Business - Archived User

### ISSUE THREAD

**Issue by blocconl** [scrthq/PSGSuite#252]
**Is your feature request related to a problem? Please describe.**
We would like to Get/Remove/Set/Update the 'G Suite Business - Archived User' license.

**Describe the solution you'd like**
We would like to use this feature in PSGSuite

**Describe alternatives you've considered**
I have seen that [GAM](https://github.com/jay0lee/GAM/blob/f0ca2e26019b16496dc14bcea080b54d43148142/src/var.py#L73) supports this license.

**Additional context**
ProductId       : 101034
ProductName : G Suite Archived User
SkuId              : 1010340002
SkuName        : G Suite Business - Archived User

**Comment by blocconl** [comment]
Never mind, found the solution.

Added this code bellow to the param set of Update-GSUser. This worked for me.

```
[parameter(Mandatory = $false)]
[Switch]
$Archived,
```

**Comment by scrthq** [comment]
hey @blocconl - Thanks for opening this up! So this is a license switch completely, I take it? First I've seen that license type tbh, but Google's added a few things over time. If that's all that is needed to get the license switched over, I'll work on adding that to the actual code base for the next release

**Comment by blocconl** [comment]
Hey @scrthq, 
Yes this is a license to reduce costs while waiting for account deletion, you can switch this license to activate / deactivate it. 

Would be nice if the 'Archived User' license could be added to Get-GSUserLicense so you have a overview of 'Archived Users'.

Thanks!

**Comment by scrthq** [comment]
hey @blocconl - so it looks like Archived User licenses might not be in the standard license type (not finding it under the [Product and SKU list](https://developers.google.com/admin-sdk/licensing/v1/how-tos/products) at least). 

I don't have any Archived User licenses purchased for any of my domains; do you get anything back at all when trying `Get-GSUserLicense` against a user with an AU license assigned? If so, what is the Product ID and SKU ID listed?

This might be similar to Cloud Identity Free licenses in that they aren't visible through the License API, seeing what I can do though

**Comment by scrthq** [comment]
@blocconl  - the `$Archived` parameter has been added in as of v2.35.0. As it stands, I don't see a documented way to get Archived User license information, so I'll wait for your test results / response to my last comment before closing this out.

**Comment by blocconl** [comment]
> @blocconl - the `$Archived` parameter has been added in as of v2.35.0. As it stands, I don't see a documented way to get Archived User license information, so I'll wait for your test results / response to my last comment before closing this out.

@scrthq - I have tested the `$Archived` parameter, and is works great! Thank you.

**Comment by scrthq** [comment]
Awesome!!! Thank you for sending those product and SKU IDs!! I'll get those added in to the *License functions ASAP. Although not officially documented, looks like GAM-X has the full list (or at least a more complete one) with a few others not documented as well: https://github.com/taers232c/GAMADV-X/blob/2da360608a13a4142c57b3416b737fa6291565e5/src/gamlib/glskus.py
