### ISSUE TITLE
Update initial setup instructions

### ISSUE THREAD

**Issue by silentmage** [scrthq/PSGSuite#30]
On the initial setup instructions, for adding the API access to the admin console, it says to enter the ServiceAccountClientID and API scopes. The client ID would not work for me, I needed to enter the actual account name with the domain at the end, ie: accountname@someweirddomain.gserviceaccount.com for the client name.

**Comment by silentmage** [comment]
![capture](https://user-images.githubusercontent.com/26926284/38615331-4a7aca68-3d5e-11e8-9ea6-538a0cf32323.JPG)

Here is a screenshot of the error received when entering the ClientID instead of the account name

**Comment by scrthq** [comment]
Using the app email won't work, it needs to be the client ID. If you're getting an error when attempting to use the ClientID, it's possible you grabbed the wrong ID. 

I'd like to know where the gap is so I know what's needed to make the instructions a bit clearer and avoid any stumbling in initial setup like this. Could you check out this guide and see if this helps? If so, I'll update my steps to follow this a bit closer: https://appaloosa-store.readme.io/docs/link-your-service-account-to-your-g-suite-domain

Jay Lee also has some pretty detailed steps for the same initial setup process for GAM. You can check those out **starting at step 26** here: https://github.com/jay0lee/GAM/wiki/CreatingClientSecretsFile


Let me know what the hangup is once you're able to get the ClientID authorized as an API client so I can update my docs accordingly!

**Comment by silentmage** [comment]
I figured it out. After creating the project I started the service account creation, but the DwD checkbox was not there so I assumed the service account ID was the clientID and tried using that in the admin console. I went back a bit later troubleshooting and had to edit the service account to see the DwD checkbox. After doing that I didn't grab the new clientID and update in the admin console. After seeing the new ID I put that into the admin console and it worked.

Here is a screenshot of the Create Service account screen. No DwD box available.

![capture](https://user-images.githubusercontent.com/26926284/38630346-a7580978-3d84-11e8-9e18-dc13ef7c5146.JPG)

Users will need to go to the credentials, click Manage Service accounts, edit the account they created and enable the DwD. Then the client ID will be visible on the via a link on the Manage Service Accounts Screen....

![capture](https://user-images.githubusercontent.com/26926284/38630477-0708134a-3d85-11e8-8d58-54db899caa19.JPG)

And on the credentials screen in the projects main page

![capture](https://user-images.githubusercontent.com/26926284/38630534-3352bdc4-3d85-11e8-9edc-551adb808a3a.JPG)

**Comment by scrthq** [comment]
Gotcha!! Thanks for the screenshots! I'll take that and work it into the Wiki page once I have a second (otherwise, feel free to update it as well if you're feeling up to it! 😄)

**Comment by scrthq** [comment]
* keeping this open until docs are updated so it doesn't fall off my plate

**Comment by silentmage** [comment]
I cloned the docs repository and added a line to the initial instructions and did a commit and push. I usually use gitlab in my local work network, so I'm not sure if I did it right for GitHub

**Comment by scrthq** [comment]
what's the remote URL/SSH for your clone? Is it still pointing at my username or is it listed as yours?

`git remote -v` to check while in the repo folder

**Comment by scrthq** [comment]
@silentmage if you'd like to just paste the updated section here, I can get it added 😃

**Comment by silentmage** [comment]
Sorry for the disappearing act. I'm looking for the clone on my machine now. I may have deleted it when trying to get a proper fork going, but got distracted and never finished

**Comment by silentmage** [comment]
OK, I can't find it so I typed it out in notepad real quick. This would be updating the Initial Setup for creating the service account and the P12 keyfile.

_________________________
7. You should have downloaded a P12 key file in your browser and be back on the Service Accounts screen. You should now see your new service account listed.
8. Click on Manage Service accounts on the far right side of the screen
9. Click the 3 dots button at the right side of the service account you just created and click edit
10. Check the box to allow "Enable G Suite Domain-wide Delegation" and click save
______________________________

The instructions can continue as you have them written from this point.

**Comment by scrthq** [comment]
Thank you!! I altered it a slight bit, let me know your feedback on this:

![image](https://user-images.githubusercontent.com/12724445/39438467-1cc9e360-4c59-11e8-9ef1-e9b64b3b6a3a.png)

**Comment by silentmage** [comment]
Looks great. Thanks for the update!

**Comment by scrthq** [comment]
You bet!
