### ISSUE TITLE
[Question] Having issues with autorization after initial setup

### ISSUE THREAD

**Issue by silentmage** [scrthq/PSGSuite#31]
I ran through the initial setup successfully, ran the setup command which went fine.  When attempting to do Get-GSUser I get an error 

Get-GSUser : Exception calling "Execute" with "0" argument(s): "Error:"unauthorized_client",Description:"Client is unauthorized to retrieve access tokens using this method.", Uri:"""

**Comment by silentmage** [comment]
https://apps-apis.google.com/a/feeds/emailsettings/2.0/,
https://mail.google.com/,
https://sites.google.com/feeds,
https://www.google.com/m8/feeds/contacts,
https://www.googleapis.com/auth/activity,
https://www.googleapis.com/auth/admin.datatransfer,
https://www.googleapis.com/auth/admin.directory,
https://www.googleapis.com/auth/admin.directory.customer,
https://www.googleapis.com/auth/admin.directory.device.mobile,
https://www.googleapis.com/auth/admin.directory.domain,
https://www.googleapis.com/auth/admin.directory.group,
https://www.googleapis.com/auth/admin.directory.orgunit,
https://www.googleapis.com/auth/admin.directory.user,
https://www.googleapis.com/auth/admin.directory.user.readonly,
https://www.googleapis.com/auth/admin.directory.user.security,
https://www.googleapis.com/auth/admin.directory.resource.calendar,
https://www.googleapis.com/auth/admin.directory.userschema,
https://www.googleapis.com/auth/admin.reports.audit.readonly,
https://www.googleapis.com/auth/admin.reports.usage.readonly,
https://www.googleapis.com/auth/apps.groups.settings,
https://www.googleapis.com/auth/apps.licensing,
https://www.googleapis.com/auth/calendar,
https://www.googleapis.com/auth/drive,
https://www.googleapis.com/auth/gmail.settings.basic,
https://www.googleapis.com/auth/gmail.settings.sharing,
https://www.googleapis.com/auth/plus.login,
https://www.googleapis.com/auth/plus.me,
https://www.googleapis.com/auth/urlshortener,
https://www.googleapis.com/auth/userinfo.email,
https://www.googleapis.com/auth/userinfo.profile

**Comment by silentmage** [comment]
Well dang. I removed the authorized client and put the client ID back in and it accepted it and now things work. My bad, thanks for the quick response!!

**Comment by scrthq** [comment]
no worries, glad it was quick and easy!
