### ISSUE TITLE
Error Message Getting All Users for Multi-Domain Customer

### ISSUE THREAD

**Issue by ryanfog** [scrthq/PSGSuite#32]
When I perform a "Get-GSUser -Filter *" the expected result is to pull back all users in G-Suite, instead I get an error message. My environment has a little over 12K accounts involved.

![capture](https://user-images.githubusercontent.com/25650327/38877573-9534e24e-4224-11e8-95f7-09247a7e3001.JPG)

**Comment by scrthq** [comment]
Hey Ryan - Checking this out now! Apologies for the delay!

**Comment by scrthq** [comment]
Can you try running the following to see if you get a different behavior? I have a feeling the default SearchBase value may be causing some headaches for your org size:

```powershell
$users = Get-GSUser -Filter * -SearchBase $null -Verbose
```

This should give you some verbose feedback showing the exact filter being sent with the command. Screenshot showing the differences:

![image](https://user-images.githubusercontent.com/12724445/39225249-ccdd1c10-4810-11e8-84e9-46b360f14e30.png)

**Comment by scrthq** [comment]
@ryanfog check my last answer and let me know if passing `$null` for the SearchBase parameter fixes this for you!

**Comment by scrthq** [comment]
@ryanfog FYI - I removed the default value for `SearchBase` in [v2.5.0](https://www.powershellgallery.com/packages/PSGSuite/2.5.0). Still pending confirmation that this was the source of the issue for you though, let me know if either v2.5.0's update fixes you or if setting the `SearchBase` value to `$null` on an earlier version does the same!

**Comment by ryanfog** [comment]
Nate,

Sorry bad news same error..

![image](https://user-images.githubusercontent.com/25650327/39584104-397ea49a-4eb7-11e8-9d64-30c0e3d44313.png)

**Comment by ryanfog** [comment]
I do have a customer ID listed and one of the primary domains of the 40 or so we have listed in Google. if we need to do a screen share or something I am open to that

**Comment by scrthq** [comment]
Gotcha! What's your Preference set to in your config? CustomerID or Domain or not set?

**Comment by scrthq** [comment]
And are you trying to list the users for all domains under your customer? or just a single domain's users?

**Comment by ryanfog** [comment]
[Variables]
;Add all persistent or environment specific variables here
AdminEmail=account@domain.com
Preference=CustomerID
CustomerID=108427614290562006643
ConfigName=PSGSuiteConfig
Domain=domain.com
P12KeyPath=C:\Users\fogler\Documents\PSGSuite\SecertSauce.p12
AppEmail=powershell@psgsuite-197900.iam.gserviceaccount.com
ServiceAccountClientID=308d85bab6e33c25fed6103225f6e2e2481e320d

**Comment by ryanfog** [comment]
All users and all domains

**Comment by scrthq** [comment]
can you try setting your CustomerID to "my_customer" as a test, then rerunning to see if any difference is made?

```powershell
# Save the current customer ID
$currentCustomerID = (Show-PSGSuiteConfig).CustomerID

# Set the config to use the generic my_customer value
Set-PSGSuiteConfig -CustomerID my_customer

# Try pulling users again (Verbose may show where it's hanging)
$users = Get-GSUser -Filter * -Verbose

# Revert your config back to normal
Set-PSGSuiteConfig -CustomerID $currentCustomerID 
```

**Comment by scrthq** [comment]
if the above works, then it may indicate the wrong CustomerID is stored in your config _OR_ that Google really doesn't like using the CustomerID there and prefers `my_customer` instead.

Next step would be to ensure that the customer ID wasn't the result of an odd copy/paste or something via this command to pull your admin user account and the customer ID property directly from there:

```powershell
Set-PSGSuiteConfig -CustomerID (Get-GSUser).CustomerID
```

**Comment by ryanfog** [comment]
Its appears you are onto something..

![image](https://user-images.githubusercontent.com/25650327/39592311-00506dd8-4ecc-11e8-8536-f7ebd7cf288c.png)

**Comment by scrthq** [comment]
lol, you're good! no dumb moves, just continual learning experiences. Glad it's sorted!!

I'm still going to add some updates to Get-GSUser to allow specific domain listing as well, as I'm sure it will be useful for users like you who manage multiple G Suite domains!

**Comment by ryanfog** [comment]
That would be awesome this we are a global company with domains like domain.fr and domain.ca etc..

**Comment by scrthq** [comment]
I should have an updated version that adds that functionality in by tonight!

**Comment by scrthq** [comment]
Just to confirm as well, you were good after setting the CustomerID in your config to `(Get-GSUser).CustomerID` still, right @ryanfog ?

**Comment by scrthq** [comment]
you _should_ be using the actual CustomerID in your config and not the `my_customer` value if you can avoid it, just want to make sure it's working once set exactly still

**Comment by ryanfog** [comment]
That is correct my config.ini file is updated with the proper customerID retrieved from Google directly.

**Comment by scrthq** [comment]
@ryanfog - added the ability to specify `-Domain $otherDomain` with v2.5.3!
