### ISSUE TITLE
Remove external IDs

### ISSUE THREAD

**Issue by cooper** [scrthq/PSGSuite#33]
Hi,

I cannot figure out how to remove external IDs from a user. I only have one external ID set, so the goal is to clear them all. I have tried things like:
```powershell
Update-GSUser someone -ExternalIds $null
```
```powershell
Update-GSUser someone -ExternalIds @()
```
but neither do the trick.

**Comment by scrthq** [comment]
Hey @cooper - What's odd is that passing `$null` returns the user object without the ExternalId's present, but pulling the user again does indeed show the ExternalId's still there. Filing as a bug and checking out what I can do to get this working as expected!

**Comment by scrthq** [comment]
Alright, Google seemed to want to take the complicated route on this one... Here's how you would need to clear External ID's with the current model (using type 'login_id' for this example); you would need to clear each external ID one by one 😞 :

```powershell
Update-GSUser -User someone -ExternalIds (Add-GSUserExternalId -Type login_id -Value $null) -Verbose
```
