### ISSUE TITLE
[Feature Request] SuperAdmin & Admin Role management

### ISSUE THREAD

**Issue by scrthq** [scrthq/PSGSuite#54]
Migrating request from issue #16

**Comment by scrthq** [comment]
Branch created to track this: https://github.com/scrthq/PSGSuite/tree/feature/AdminMgmt_issue54

**Comment by scrthq** [comment]
@nsclarkson - You can follow this issue for the Admin Role / Delegation Mgmt updates. Should hopefully have those rolled out soon!

**Comment by nsclarkson** [comment]
@scrthq Awesome thanks!

**Comment by scrthq** [comment]
@nsclarkson deployed AdminRole and AdminRoleAssignment functions as well as added the `-IsAdmin` switch parameter on `Update-GSUser` in v2.9.0! Check it out and let me know if you have any questions!
