### ISSUE TITLE
PSGSuite v2.0.0 - Development / Testing

### ISSUE THREAD

**Issue by scrthq** [scrthq/PSGSuite#6]
Issue to track development and testing of PSGSuite v2.0.0

### Functions To Convert/Build

> _Possible breaking changes on Gmail Delegate functions due to Google deprecating the Email Settings API but still not supporting Inbox Delegation in the Gmail API_

| Function                       | Conversion | New   | Complete |
| :----------------------------: | :--------: | :---: | :------: |
| Add-GSGmailDelegate*           | ✔️         |       | ❗️        |
| Add-GSGmailFilter              | ✔️         |       | ✔️       |
| Get-GSGmailDelegates*          | ✔️         |       | ❗️        |
| Get-GSGmailFilterList          | ✔️         |       | ✔️       |
| Get-GSGmailLabelList           | ✔️         |       | ✔️       |
| Remove-GSGmailDelegate*        | ✔️         |       | ❗️        |
| Remove-GSGmailFilter           | ✔️         |       | ✔️       |
| Add-GSDriveFilePermissions     | ✔️         |       | ✔️       |
| Clear-GSSheet                  | ✔️         |       | ✔️       |
| Copy-GSDriveFile               | ✔️         |       | ✔️       |
| Copy-GSSheet                   | ✔️         |       | ✔️       |
| Get-GSDriveFile                | ✔️         |       | ✔️       |
| Get-GSDriveFileInfo            | ✔️         |       | ✔️       |
| Get-GSDriveFileList            | ✔️         |       | ✔️       |
| Get-GSDriveFilePermissionsList | ✔️         |       | ✔️       |
| Get-GSSheetInfo                | ✔️         |       | ✔️       |
| Get-GSTeamDrive                | ✔️         |       | ✔️       |
| Get-GSTeamDrivesList           | ✔️         |       | ✔️       |
| Import-GSSheet                 | ✔️         |       | ✔️       |
| New-GSDriveFile                | ✔️         |       | ✔️       |
| New-GSSheet                    | ✔️         |       | ✔️       |
| New-GSTeamDrive                | ✔️         |       | ✔️       |
| Remove-GSTeamDrive             | ✔️         |       | ✔️       |
| Update-GSDriveFile             | ✔️         |       | ✔️       |
| Update-GSSheetValue            | ✔️         |       | ✔️       |
| Update-GSTeamDrive             | ✔️         |       | ✔️       |
| Start-GSDriveFileUpload        |            | ✔️    | ✔️       |
| Get-GSDriveFileUploadStatus    |            | ✔️    | ✔️       |

### Other Tasks

- [x] Update documentation
- [x] Build out ChangeLog to document any breaking changes
- [x] Update Pester Tests
- [x] Add in CI configuration for AppVeyor
    - [x] ~~Build out Travis CI tests for Linux/macOS?~~ Skipped for now, using pwsh support in AppVeyor to test PowerShell Core compatibility
- [x] Clean up PSGSuite2 to PSGSuite in prep for deployment to PSGallery
- [x] DEPLOY PSGSuite 2.0.0!

**Comment by scrthq** [comment]
@wesleykirkland adding this for continued discussion around v2.0.0 testing/dev

**Comment by scrthq** [comment]
## Remaining Tasks (roughly)

| Function                       | Conversion | New |
| ------------------------------ | ---------- | --- |
| Add-GSGmailDelegate            | X          |
| Add-GSGmailFilter              | X          |
| Get-GSGmailDelegates           | X          |
| Get-GSGmailFilterList          | X          |
| Get-GSGmailLabelList           | X          |
| Remove-GSGmailDelegate         | X          |
| Remove-GSGmailFilter           | X          |
| Add-GSDriveFilePermissions     | X          |
| Clear-GSSheet                  | X          |
| Copy-GSDriveFile               | X          |
| Copy-GSSheet                   | X          |
| Get-GSDriveFile                | X          |
| Get-GSDriveFileInfo            | X          |
| Get-GSDriveFileList            | X          |
| Get-GSDriveFilePermissionsList | X          |
| Get-GSSheetInfo                | X          |
| Get-GSTeamDrive                | X          |
| Get-GSTeamDrivesList           | X          |
| Get-GSToken                    | X          |
| Import-GSSheet                 | X          |
| New-GSDriveFile                | X          |
| New-GSSheet                    | X          |
| New-GSTeamDrive                | X          |
| Remove-GSTeamDrive             | X          |
| Revoke-GSToken                 | X          |
| Switch-PSGSuiteDomain          | X          |
| Update-GSDriveFile             | X          |
| Update-GSSheetValue            | X          |
| Update-GSTeamDrive             | X          |
| Copy-ToGSDrive | | X

**Comment by wesleykirkland** [comment]
@scrthq I got started with your example, for some reason generating the config like that never occurred to me. Just putting this out there but I'm nuking the conf file each time it runs and rebuilding it on the fly to bypass the encryption settings.

The functions I needed most were these and their working perfectly!
get-gsgrouplist
get-gsgroupmemberlist
get-gsuserlist

**Comment by scrthq** [comment]
@wesleykirkland awesome! Sure, if you know the values to begin with, being able to read the config is kind of irrelevant at that point because you already have the secrets. The main thing to keep locked are your P12 keys, which should hopefully have filesystem permissions protecting them as well. Once you're done testing and you have a config built out, delete your test script with your secrets on it.

And yup! those functions (really, all Directory API functions) are done. The only things I have left to wrap up are Drive and Sheets API functions, then she should be good to ship!

Let me know if you hit any snags! You should be able to get pretty good pipeline support also, even from AD User objects (all `User` params accept `ValueFromPipelineByPropertyName` with `mail` aliased)

Cheers!

**Comment by scrthq** [comment]
@wesleykirkland also, generating the config like that wouldn't have worked with the current version of PSGSuite, single-file nested configs are something I've built into this release 🗡

**Comment by scrthq** [comment]
@wesleykirkland little update to those *List functions as well: if you take off the "List" portion of the function name, they should work the exact same (working on cleaning up the *List files into a single file).

I.e.

`Get-GSUser` will behave the same as `Get-GSUserList` if you pass no args. The short version has the same parameters as the long version though, so you should find perfect interoperability. Also, Get-GSUser has been built out to be syntactically similar to Get-ADUser, if you're familiar with running AD commands:

```powershell
Get-GSUser -Filter "IsAdmin -eq '$true'" -SearchBase '/Users' -SearchScope OneLevel
```

That would get you all Admin users in the Users OU and one level deeper.

**Comment by scrthq** [comment]
confirmed PS4.0 works fine with the module, the dependency module Configuration 1.2.0 seems to break though in PS3.0 due to not following `-ErrorAction Ignore` used withing it (it's still throwing a Terminating Error).

PS 3.0 incompatibility isn't a huge loss, so it'll be backburnered until I can get Configuration + PSGSuite working in PS 3.0.

**Comment by scrthq** [comment]
Drive file upload functions done and all previously existing and relevant functions converted for v2.0.0. 

Prepping the remaining items to gear up for release!

**Comment by scrthq** [comment]
PSGSuite 2.0.0 released!

Wiki has been updated, 100% of functions also have comment based help as well so the documentation is at your fingertips while using the module directly.

Please check out the README for any breaking changes!

PowerShell Gallery link: https://www.powershellgallery.com/packages/PSGSuite/2.0.0


Cheers!
