### ISSUE TITLE
[Issue] Send-GmailMessage is fitting message body to a set width

### ISSUE THREAD

**Issue by jtwaddle** [scrthq/PSGSuite#76]
**Describe the bug**
Send-GmailMessage is fitting the body of the message to a specific width instead of sending the text the way it was passed into the function.

**To Reproduce**
1. Use Send-GmailMessage and make sure to have enough text in a line to go beyond the set width.

**Expected behavior**
I would expect the Send-GmailMessage to send the message body as I pass it.  It appears to be setting the message to a specific width.  Here are two screenshots.  One showing the message with the full width in GMail and the other showing it shrunk when sending it using Send-GMailMessage.

![fullmessage](https://user-images.githubusercontent.com/16723550/42769041-b74037f4-88e6-11e8-96a1-6f460b86c136.PNG)
![shrunkmessage](https://user-images.githubusercontent.com/16723550/42769048-b9131db2-88e6-11e8-8b82-e09dd08eff95.PNG)

**Comment by scrthq** [comment]
thanks, @jtwaddle ! PSGSuite uses MimeKit underneath to build the raw Mime message... I'll check it out and see if any tweaking can be done to get it to match what's expected!

**Comment by scrthq** [comment]
Also - worth noting that I'm using PSGSuite 2.12.0 here, which included updates to the Google .NET SDK's inside.

The issue you're describing seems to be real, as I've found another report of someone using the same setup (MimeKit + Gmail .NET SDK) to send messages and the text was being wrapped: https://stackoverflow.com/questions/47425399/send-message-via-gmailservice-api-auto-wraps-lines

**Comment by scrthq** [comment]
hey @jtwaddle - closing this out since everything is working fine for me since testing. If you haven't updated to the latest version of PSGSuite, I invite you to do so and try this out!
