### ISSUE TITLE
Get-GSUser output

### ISSUE THREAD

**Issue by IronKane2** [scrthq/PSGSuite#78]
I'd like to be able to output the results of Get-GSUser to a Powershell $ variable.  Currently, it returns just "Google.Apis.Admin.Directory.directory_v1.Data.User" unless I run the command without trying to add it to a $ variable

**Comment by scrthq** [comment]
hey @IronKane2 - can you post some sample code? Based on your output, it looks like you're trying to cast the results to string, which by default returns the type name of the object being cast if there's no working `ToString()` method

Here's what I expect is happening by command in the below screenshot:
1. Run `Get-GSUser` and store in variable `$user` (defaults to the AdminEmail in the config)
2. Cast `$user` to string by surrounding it in quotes (`"$user"`), replicating your issue
3. Just run `$user` and get the full object back

![image](https://user-images.githubusercontent.com/12724445/43930096-47a3d0f2-9bfd-11e8-97c9-9d0d57381342.png)

**Comment by scrthq** [comment]
You can do the same thing with almost any object lacking a `ToString()` method:

```powershell
PS > $hash = @{}
PS > "$hash"
```
Output:
```
System.Collections.Hashtable
```

**Comment by IronKane2** [comment]
I figured out how to do it:
[Google.Apis.Admin.Directory.directory_v1.Data.User]$GAFE = Get-GSUser -User $Student.mail

I had to implicitly declare the variable type before loading it.

**Comment by scrthq** [comment]
@IronKane2 shouldn't need to do that at all

**Comment by IronKane2** [comment]
After a reboot all was well.  thanks.

**Comment by scrthq** [comment]
@IronKane2 sweet, glad to hear you're sorted out!
