### ISSUE TITLE
[Issue] Get-GSGroup Returning Error

### ISSUE THREAD

**Issue by scrthq** [scrthq/PSGSuite#82]
@queks advised about issue on #77 : https://github.com/scrthq/PSGSuite/issues/77#issuecomment-416626873

![psgsuite_error](https://user-images.githubusercontent.com/34079282/44732672-68c36200-ab18-11e8-8c2a-bfe5e5d5bc98.png)

can you provide the command you're running with anything sensitive removed? I'm not able to replicate that on my end when calling `Get-GSGroup` which calls `Get-GSGroupListPrivate` underneath it.

**Comment by scrthq** [comment]
My attempts to replicate:

![image](https://user-images.githubusercontent.com/12724445/44733361-0ed98280-aaad-11e8-93a5-c9465fbc9aa7.png)

**Comment by queks** [comment]
Its somewhere along the lines of:

foreach ($student in $SIS)
{
    try {$G_Person = Get-GSUser -User $student.username} catch{}
    if ($G_Person)
    {
    $G_ClassOf = Get-GSGroup -Where_IsAMember $G_Person | where {$_.name -match 'Class of '}
    }
}

Basically I'm trying to audit all the student records in our SIS to make sure they have G Suite accounts and they are in the proper 'Class Of' group.

The error doesn't appear consistently - i get it sometimes and sometimes not.

**Comment by scrthq** [comment]
ah, gotcha. Looks like you're passing the full Google User object to `-Where_IsAMember`.

Try this:

```powershell
foreach ($student in $SIS) {
    try {
        $G_Person = Get-GSUser -User $student.username
    }
    catch {
    }
    if ($G_Person) {
        $G_ClassOf = Get-GSGroup -Where_IsAMember $G_Person.PrimaryEmail | where {$_.name -match 'Class of '}
    }
}
```

**Comment by queks** [comment]
Thanks! Seems to work fine now!
Just thought it was odd that before, it would only throw an error intermittently.

**Comment by scrthq** [comment]
definitely odd that it worked at all before tbh! I'm glad you're sorted now though!
