### ISSUE TITLE
Possibility to update user account photo

### ISSUE THREAD

**Issue by lucafabbri365** [scrthq/PSGSuite#90]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to retrieve G Suite user photo only (Get-GSUserPhoto).

**Describe the solution you'd like**
The possibility to update user account photo (Update-GSUserPhoto)

**Comment by scrthq** [comment]
Hey @lucafabbri365 - Thanks for submitting the feature request! This should 100% be doable, I'll keep you updated!

**Comment by lucafabbri365** [comment]
Thank you @scrthq  !!!
Note: PSGSuite is helping the company I'm working for, to migrate about 1100 users from third party collaboration suite ;-).

**Comment by scrthq** [comment]
@lucafabbri365 that's so awesome to hear!! I'm glad PSGSuite is doing wonders for you 😃

**Comment by scrthq** [comment]
Alright, so `Update-GSUserPhoto` is done and I'm able to validate by running `Get-GSUserPhoto -OutFilePath . -OutFileFormat PNG` after updating my own photo. Google's Web UI is a bit slow to update though, looks like cache on Google's servers and not in-browser. I'm giving it until tomorrow before I push out a new release and wrapping a couple other fixes in with it for #87 💪 . Also including `Remove-GSUserPhoto` for full UserPhoto API coverage.

**Comment by scrthq** [comment]
v2.15.1 deploying now with the additional UserPhoto functions! 🚀

**Comment by lucafabbri365** [comment]
Simply Great !!

Thank you @scrthq !!

**Comment by scrthq** [comment]
you bet!
