### ISSUE TITLE
Get-GSGroup and Subdomains

### ISSUE THREAD

**Issue by IronKane2** [scrthq/PSGSuite#96]
Get-GSGroup can find a group in a subdomain by exact email address, but it won't pull up any of these groups in List Mode so it's not filterable.  Can a -Domain parameter be added?

**Comment by scrthq** [comment]
Hey @IronKane2 - Definitely can be added! Excellent suggestion 😄 Currently, it looks at the `Preference` value in your PSGSuite config and will set the Domain or Customer scope depending on that. Should have this rolled out by tonight!

**Comment by scrthq** [comment]
CC @phatmandrake - I should be able to get Group Query functionality in there as well (@phatmandrake requested this in a previous issue and I actually just got it working with the .NET SDK).

**Comment by IronKane2** [comment]
That'll be awesome.  I have a few thousand leftover groups from a former vendor to remove.

**Comment by scrthq** [comment]
Could you test one thing for me and see if `Get-GSGroup` gives you the list for that specific Subdomain?

```powershell
# Replace with actual subdomain you're looking for
$thatSubDomain = 'oldvendor.com'

# Store the current config in a var so we can easily revert after testing
$currentConf = Show-PSGSuiteConfig

# Update the config with the specific subdomain you're looking to
# query as the Domain and set Preference to 'Domain'
Set-PSGSuiteConfig -Domain $thatSubDomain -Preference Domain

# Run Get-GSGroup with verbose enabled, you should see the following verbose message:
# "VERBOSE: Getting all G Suite groups for domain '$thatSubDomain'"
$groups = Get-GSGroup -Verbose

# Restore your original config
$currentConf | Set-PSGSuiteConfig

# Explore the Group list to ensure it has the groups you're expecting
($groups | Where-Object {$_.Email -like "*@$($thatSubDomain)"}).Count
```

**Comment by IronKane2** [comment]
PS C:\> $groups = Get-GSGroup -Verbose
VERBOSE: Building ServiceAccountCredential from P12Key as user 'srcampbell@djusd.net'
VERBOSE: Getting all G Suite groups for domain 'djusdstudent.org'
Get-GSGroupListPrivate : Exception calling "Execute" with "0" argument(s): "Google.Apis.Requests.RequestError
Domain not found. [404]
Errors [
	Message[Domain not found.] Location[ - ] Reason[notFound] Domain[global]
]
"
At line:74 char:21
+                     Get-GSGroupListPrivate @PSBoundParameters
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GSGroupListPrivate

**Comment by scrthq** [comment]
🤔 odd! I'm assuming that domain is within the domains your overall customer account owns, correct?

**Comment by IronKane2** [comment]
djusd.net is parent domain of djusdstudents.org.  I'm SA and have full control of both.  I'm able to create djusdstudents.org accounts with New-GSUser for which I'll be eternally grateful.

**Comment by IronKane2** [comment]
PS C:\> Get-GSGroup | ?{$_.email -like '*@djusdstudents.org'} returns nothing.  While doing Get-GSGroup | ?{$_.email -like '*willett*'} will pull up djusd.net groups

**Comment by IronKane2** [comment]
Preference is set to "Domain"

**Comment by scrthq** [comment]
Can you set your preference to "CustomerID" instead and retry that `Get-GSGroup`? This should list out every group for all domains your customer owns. With Preference set to Domain, it will only search the Domain name listed on the config.

**Comment by IronKane2** [comment]
That did it!  And it's still scrolling lol

**Comment by IronKane2** [comment]
12,688 groups.  I believe you've been a big help.

**Comment by scrthq** [comment]
nice! Your original request is still very valid though and it's still on my TODO list to get handled tonight 💪

**Comment by scrthq** [comment]
PSGSuite v2.15.4 now available on the PS Gallery!

Update notes:

## 2.15.4

* [Issue #96](https://github.com/scrthq/PSGSuite/issues/96)
  * Updated the following on `Get-GSGroup`:
    * Set default scope to `Customer` so that getting the list of groups expectedly gets all of them, not just the ones in your primary domain
    * Added `Domain` parameter to specify which domain to list groups from your customer account
    * Added `Filter` parameter to only list groups matching the Group query syntax
    * Moved the `Get-GSGroupListPrivate` private function into the body of `Get-GSGroup` for error clarity
* Others:
  * Moved the `Get-GSUserListPrivate` private function into the body of `Get-GSUser` for error clarity
  * Improved error handling for User and Message List functions when there are no results.

**Comment by efrank85** [comment]
Hello,

I am having a similar issue I cannot get around. I've set my PSGsuiteConfig Preference to "CustomerID" as instructed. However, I am still receiving the below error. 

Get-GSGroup : Exception calling "Execute" with "0" argument(s): "Google.Apis.Requests.RequestError
Bad Request [400]
Errors [
        Message[Bad Request] Location[ - ] Reason[badRequest] Domain[global]
]
"
At line:1 char:1
+ Get-GSGroup
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GSGroup

I can run Get-GSGroup against an individual group or CSV import but not the command by itself. I am an SA in GSuite and have literally enabled every API that has the word "Group" in it trying to troubleshoot. Any help on this issue at all would be much appreciated.
